### ISSUE TITLE
scaling recursive to a large number of datasets

### ISSUE THREAD

**Issue by lotheac** [oetiker/znapzend#104]
I have several thousands of filesystems (user home directories) and would like to use znapzend recursively to back those up to a remote host. I configured the dataset with recursive=on, but running znapzend with --debug --no-action --runonce I can see that it is opening a new ssh connection to the remote host for every child dataset just to list their snapshots (the same is also done locally). This is not feasible with a large number of child datasets; the same information could be acquired with a single 'zfs list -r' instead.

It hasn't gotten to the sending part yet, so I can't speak as to issues there yet. Our current backup script uses a combination of zfs-auto-snapshot (which does snapshot -r, destroy -r), zfs list -r (both locally and remotely) as well as zfs send -R (because -r is not available in illumos zfs) to limit the number of ssh connections.

**Comment by epruesse** [comment]
I think the ```ControlMaster``` setting for SSH should go into the documentation. Given that you just removed ```-o Compression=yes``` in favor of ```.ssh/config``` settings, perhaps a brief section with recommended SSH settings would be simple to do and help people make the most out of ZnapZend (w/o the ControlMaster settings, ```znapzendztatz -r``` is way too slow to be useful).

**Comment by oetiker** [comment]
@epruesse yes ControlMaster is really cool ... if you happen to run on openssh and not on sunssh :) ... but smartos and omnios have recently ditched sunssh, so this has become good option ... can you create a PR for the docu changes ?

**Comment by lotheac** [comment]
FWIW, I no longer need this feature -- experience has shown that a large number of datasets is problematic in other ways too: eg. it can use a lot of memory, and things can get messy with send -R if a single dataset fails to be received for some reason - it will fail the entire send (which can be quite large) and possibly leave the receiving side in a state that requires manual intervention. So I'm closing this; feel free to reopen if you think send -R is worth it.
