### ISSUE TITLE
-snap-command API

### ISSUE THREAD

**Issue by ser** [oetiker/znapzend#122]
It would be useful if scripts run from pre and post commands could get current backup parameters, for example current snapshot name, etc.

**Comment by hadfl** [comment]
could you be more specific about the 'etc.'?

what kind of information would you like to have available for pre/post commands except current snapshot name?

**Comment by ser** [comment]
hi :)
i think two parameters would be cool to have:

1. current snapshot name
1. time of processing of that backupset

**Comment by hadfl** [comment]
--> https://github.com/oetiker/znapzend/pull/128
```$ZNAP_NAME``` and ```$ZNAP_TIME```
