### ISSUE TITLE
install should not create thridparty directory in prefix directory

### ISSUE THREAD

**Issue by diekhans** [oetiker/znapzend#125]
thirdparty software install creates a directory ${prefix}/thirdparty.  This violates unix/linux filesystem
organization rules (seee man hier).  These should probably go in ${prefix}/lib/znapzend/thirdparty

**Comment by oetiker** [comment]
the idea is to install in /opt/znapzend-$version in that case all is fine. but I agree if you want to throw it into /usr then this does not work well ...

**Comment by dewi-ny-je** [comment]
Be careful with zones: /usr/local is inherited and /opt is not
http://compgroups.net/comp.unix.solaris/-usr-local/354465
