### ISSUE TITLE
no documentation on behavior with rotating backup disk

### ISSUE THREAD

**Issue by diekhans** [oetiker/znapzend#126]
It's unclear what will happen when back disk is rotated.  Does it create a backup snapshot that brings the rotated disk up to date or only backup since the previous backup to the previous disk.

**Comment by hadfl** [comment]
if no snapshot exists on the backup disk, yet. znapzend will send only the last snapshot (initialisation).

if there exists at least one common snapshot on the source and backup destination, znapzend will send all snapshots from the last common to the backup destination.

**Comment by diekhans** [comment]
Thank you.  Suggest added the above answer to the manual page. Very nice package!

**Comment by oetiker** [comment]
@diekhans how about providing a patch for the embedded doc so the the information appears in a place where you would have expected it to appear ?
