### ISSUE TITLE
znapzendzetup create fails indicating it can't find SRC filesystem being created

### ISSUE THREAD

**Issue by diekhans** [oetiker/znapzend#130]
sudo znapzendzetup create --tsformat='%Y-%m-%dT%H:%M:%SZ'  SRC  '1min=>10min,5min=>20min' /mnt/test/src  DST '5min=>1year' /mnt/test/bak

ERROR: filesystem /mnt/test/src does not exist

FreeBSD  9.3-RELEASE-p5
 perl 5 v5.18.4)

**Comment by hadfl** [comment]
i don't think that '/mnt/test/src' is a valid zfs dataset. it looks more like the mountpoint of the dataset...

you have to specify the zfs dataset, not the mountpoint

**Comment by diekhans** [comment]
Thanks!! I misinterpreted the complain about file system..
