### ISSUE TITLE
Install with brew on OSX

### ISSUE THREAD

**Issue by lenada** [oetiker/znapzend#131]
It would be very convenient for znapzend users on osx to use brew for installation and updates.
something like the following homebrew Formula `znapzend.rb` needs to be shipped to @homebrew.

https://gist.github.com/lenada/e773a65aa9d37c0eb42c

@oetiker what is your general take on all those package managers out there? would you be willing to maintain and update some, for example the homebrew formula, linux apt, etc. yourself? or are you rather looking for external maintainers.
should I PR my Formula against https://github.com/Homebrew/homebrew ? who should do so on the next release?

by the way, znapzend is a really great tool  :) appreciated!

**Comment by lenada** [comment]
I also would be really interested in getting znapzend into freebsd ports :neckbeard:

**Comment by oetiker** [comment]
@lenada OS are certainly welcome ... I had a look at your homebrew gist. It would be preferable if it worked from the standard source version though and not from the pre-built one ... the pre-build is really a hack ...

**Comment by lenada** [comment]
@oetiker I gave the source version a try first but failed due to `make get-thirdparty-modules` (also related to #125).

also symlinks to executables do not work because of `$FindBin::Bin/../lib` & `$FindBin::Bin/../thirdparty`

**Comment by oetiker** [comment]
but the source version and the pre-built are the same, except that get-thirdparty-modules has been executed prior to make install ...

in anyway, it might be a good idea to replace the FindBin magic upon installation using the proper path

**Comment by lenada** [comment]
@oetiker problem is ./configure --prefix=/usr/local/Cellar/znapzend/0.14.0 fails on first run due to missing thirdparty dependencies, which causes the build to fail. I probably could try to enforce/override the exit status, but that seems even more hackish.

IMHO it would be nice to have a configure flag to skip the thirdparty check. That way I could install the perl/mojo dependencies through brew and get rid of the thirdparty directory alltogether.

`/usr/bin/gnumake get-thirdparty-modules` also has a dependency on `wget` which is not installed on os x per default.

**Comment by oetiker** [comment]
would curl be better ?

```
./configure --prefix=/usr/local/Cellar/znapzend/0.14.0 || true
gnumake get-thirdparty-modules
```

**Comment by lenada** [comment]
@oetiker for os x curl is preinstalled. But wget vs curl etc. may vary across operating systems / distros?

**Comment by oetiker** [comment]
configure could check

**Comment by oetiker** [comment]
@lenada znapzend does work on opensfsonosx ? just asking, to be sure the effort ist not wasted

**Comment by lenada** [comment]
@oetiker yes it works like a charm

**Comment by oetiker** [comment]
please try master ... thirdparty is gone ...

**Comment by ilovezfs** [comment]
As a start, anyone can now

brew tap ilovezfs/znapzend
brew install --HEAD znapzend

The tap is "hosted" here: https://github.com/ilovezfs/homebrew-znapzend

**Comment by lenada** [comment]
@ilovezfs great thank you :dancers:
