### ISSUE TITLE
Skip network replication if remote destination is not available

### ISSUE THREAD

**Issue by marco-prati** [oetiker/znapzend#133]
It would be nice to have the daemon skip the network replication of a snapshot if the remote destination is not available. It may be needed in case of znapzend running on laptops while not having a network connection available: the daemon can continue to snapshot the datasets, and as soon as the destination becomes reachable, the repliction can occur.
 
Now it stops and exits with error (while checking for mbuffer on the remote side):
sudo ./bin/znapzend --debug                                                                           
ssh: connect to host <host> port 22: Connection timed out
ssh: connect to host <host> port 22: No route to host
ERROR: executable '/usr/local/bin/mbuffer' does not exist on root@<host>

This change is also needed on the znapzendztatz command.

**Comment by hadfl** [comment]
this has been addressed already: https://github.com/oetiker/znapzend/issues/107
fixed with https://github.com/oetiker/znapzend/pull/118

this fix has been merged to master but is not in the latest release (v0.14.0), you'll have to build it from the master branch...

**Comment by marco-prati** [comment]
Ok, i've checked and now it won't exit anymore in case of network failure, thanks.
Can it be useful to refresh DST status periodically? For example now I have my snapshots being taken, but the replication is disabled even if I am connected to the network where the DST resides (because of DST removed in daemon init). If the destination becomes available again it can be re-added as a valid DST thus enabling the replication job.
For now restarting the daemon is the only workaround that i've found.

**Comment by hadfl** [comment]
your are right. i will implement a recheck if the destination has been unavailable for every new run.
