### ISSUE TITLE
no new remote filesets when running with --debug

### ISSUE THREAD

**Issue by oetiker** [oetiker/znapzend#135]
<rjeschmi> I noticed when running znapzend in debug to watch the output that it won't create new filesystems on the remote end. If I restart it with "runonce" everything creates remotely as expected
<rjeschmi> it isn't a big deal since I don't have a huge number of new filesystems, but I thought I'd ask

**Comment by hadfl** [comment]
it would be good to know the exact command line incantation.
was the ```--debug``` run with ```--noaction```?

znapzend does *not* create any filesystems on the destination. the base dataset must be created manually. all new sub-datasets will then be created on the destination with send/recv.

**Comment by hadfl** [comment]
fixed w/ `--autoCreation`
