### ISSUE TITLE
problem starting binary

### ISSUE THREAD

**Issue by emmelmann** [oetiker/znapzend#136]
hi, i get this message when starting znapzendzetup binary on openindiana oi_151a7:

./znapzendzetup
Version mismatch between Carp 1.08 (/usr/perl5/5.10.0/lib/Carp.pm) and Carp::Heavy 1.3301 (/home/frederic/znapzend-prebuilt-0.14.0/bin/../thirdparty/lib/perl5/Carp/Heavy.pm).  Did you alter @INC after Carp was loaded?
Compilation failed in require at /usr/perl5/5.10.0/lib/File/Temp.pm line 152.
Compilation failed in require at ./znapzendzetup line 10.
BEGIN failed--compilation aborted at ./znapzendzetup line 10.

can somebody help?
thank you
frederic

**Comment by oetiker** [comment]
we have only tested this with perl 5.10.1 ... two things you might want to try

a) get a recent perl

b) install the non-prebuilt version

cheers
tobi
