### ISSUE TITLE
znapzend 0.14 on RHEL7/OL7

### ISSUE THREAD

**Issue by budachst** [oetiker/znapzend#142]
Hi,

I am trying to compile znapzend-0.14 on one of my OL7 VMs and had to run the
 /usr/bin/gmake get-thirdparty-modules command, due to missing dependancies. After installint ExtUtilsMakeMaker through yum that worked and resultet in this:

Building Mojolicious-5.69 ... OK
Successfully installed Mojolicious-5.69
--> Working on Mojo::IOLoop::ForkCall
Fetching http://www.cpan.org/authors/id/J/JB/JBERGER/Mojo-IOLoop-ForkCall-0.15.tar.gz ... OK
Configuring Mojo-IOLoop-ForkCall-0.15 ... OK
==> Found dependencies: IO::Pipely
--> Working on IO::Pipely
Fetching http://www.cpan.org/authors/id/R/RC/RCAPUTO/IO-Pipely-0.005.tar.gz ... OK
Configuring IO-Pipely-0.005 ... OK
Building IO-Pipely-0.005 ... OK
Successfully installed IO-Pipely-0.005
Building Mojo-IOLoop-ForkCall-0.15 ... OK
Successfully installed Mojo-IOLoop-ForkCall-0.15
21 distributions installed

However, when I am trying to run configure znapzend-0.14 if errors out with this message:

checking checking for perl module 'Mojolicious'... Failed
checking checking for perl module 'Mojo::IOLoop::ForkCall'... Failed
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating init/znapzend.xml
config.status: WARNING:  'init/znapzend.xml.in' seems to ignore the --datarootdir setting

** SOME PERL MODULES ARE MISSING ******************************

If you know where perl can find the missing modules, set
the PERL5LIB environment variable accordingly.

You can also install a local copy of the Perl modules by running

   /usr/bin/gmake get-thirdparty-modules

You may want to run configure again after that to make sure
all modules are installed

So, I did that, but to no avail. Any hints on how to get that resolved?

Thanks,
Stephan

**Comment by budachst** [comment]
I ended up installing the missing dependencies manually, by subsequently installing each perl rpm as spit out as missing when running znapzend. Afterwards, compilling went also smoothly. ;)

So, case closed, I guess.

Cheers,
Stephan

**Comment by oetiker** [comment]
Stephan, I have a new build system which I will integrate ... I carries all dependent perl modules along, that might simplify setup ... 
stay tuned ...
