### ISSUE TITLE
znapzend and tapes?

### ISSUE THREAD

**Issue by ser** [oetiker/znapzend#143]
Any ideas how one could marry znapzend with tape backup?

**Comment by hadfl** [comment]
it is planned to rewrite large portions of znapzend to make it more flexible (especially w/ respect to adding new features/functionality).

i think after that step is done it should be quite 'easy' to extend znapzend to write to tape backups (as it will be possible to write backups to files on non zfs filesystems).

**Comment by rottegift** [comment]
When the zfs sendstream changes land across openzfs ports (notably per-object checksums, force-partial-receives (in the face of bad objects) and resumable receives (for utility)), the output of zfs send will be reasonably good for archival storage on its own.    Until then, one bit error, or one bug (e.g. https://github.com/zfsonlinux/zfs/issues/2210) and your archived sendstream is practically unrecoverable.

( Some details starting at p. 19 in ahrens's slide deck here... http://www.slideshare.net/MatthewAhrens/openzfs-send-and-receive )
