### ISSUE TITLE
How to snapshot SRC frequently and send to DST infrequently?

### ISSUE THREAD

**Issue by rottegift** [oetiker/znapzend#144]
The use case here is that a dst goes into low-power mode when not poked for several minutes at a time, and the src is undergoing rapid evolution that may require use of a snapshot (say, to rollback, or to clone).   Additionally, in this particular case, the deltas between snapshots are quite large compared to the foo pool.

```
src             = foo/bar
src_plan        = 6hours=>10minutes,1day=>20minutes,3days=>1hour,7days=>2hours,2weeks=>1day
dst_0           = user@remote:remotebackup/bar
dst_0_plan      = 7days=>6hours,30days=>12hours,90days=>1day,1year=>1week,10years=>1month
```

... but this causes a zfs send/recv every 10 minutes, and some of the 10-minute snapshots' sendstreams are big enough that the zfs recv does not finish within 10 minutes.

With this configuration, I think znapzend should only talk to remote every six hours.    

(Also, but less importantly, sending an -i stream rather than sending an -I stream would reduce the traffic on the network and the extra work on the dst of receiving the intermediate snapshots only to have many of them destroyed by znapzend.)

**Comment by hadfl** [comment]
it is planned to make znapzend cleverer concerning sending snapshots to destinations (e.g. sending only when necessary as you pointed out and sending only snapshots that 'belong' to znapzend)

**Comment by rottegift** [comment]
Cool.   

I actually do use snapshots that don't "belong" to znapzend, essentially like this:

```
zfs snapshot pool/dataset@some-milestone
zfs bookmark pool/dataset@some-milestone pool/dataset#some-milestone
sleep 432000 # well, not literally
zfs destroy pool/dataset@some-milestone
```

The some-milestone snapshot gets copied over by znapzend and stays put.  If there's ever some sort of problem (manual intervention, some extra cleanup script going mad when desperate to free up space on a small ssd-based pool, whatever) that causes there to be no snapshots in common between source and destination, recovering from a bookmark with 

```
zfs send -i pool/dataset#some-milestone  pool/dataset@existing snapshot | ... zfs recv -vuF remote/from_pool/dataset -vuF
```

is an easy enough fix.

I guess that's best done with a dataset property that indicates whether or not to send intermediate snapshots (including ones not owned by znapzend) on a dst-by-dst basis.

Orthogonally, any sort of "good enough" way to avoid waking up each dst much more frequently than "intA" (in "retA=>intA,retB=>intB,...") is probably fine, so I'm happy that it is planned.    Have znapzendzetup throw a warning if the longest src ret=>int pair will roll away snapshots too soon for them to reliably get to all the dsts.
