### ISSUE TITLE
DST plan names strip out '-' character.

### ISSUE THREAD

**Issue by DougHughes** [oetiker/znapzend#145]
I tried to use the destination machine name in the name of the plan (no particular reason, it just seemed natural), but we use '-' in machine names. The regular expression that builds the backup plan tags that it puts into zfs seems to strip everything after and including the first '-' found. Since '-' is an allowed character in a zfs user property, it seems overly aggressive to filter in this way.

**Comment by hadfl** [comment]
fixed: https://github.com/oetiker/znapzend/pull/147
