### ISSUE TITLE
mbuffer vs ssh

### ISSUE THREAD

**Issue by DougHughes** [oetiker/znapzend#146]
I noticed my znapzend was only getting about 1.2MB/sec and thought that was pretty low, so I went to look, ant it looks like ssh is being used for the actual transport with mbuffer only being used on the far end. e.g. client side zfs -> ssh  --------- server ssh -> mbuffer -> zfs

Is there a reason that the it doesn't use mbuffer tcp directly?

Here's my evidence:
server side:
lots of reads on fd0 of mbuffer, so pfiles on mbuffer pid:
root@x4275-3-15-20:/root# pfiles 3603
3603:   /opt/omni/bin/mbuffer -q -s 128k -W 60 -m 10M
  Current rlimit: 256 file descriptors
   0: S_IFSOCK mode:0666 dev:532,0 ino:5813 uid:0 gid:0 rdev:0,0
      O_RDWR
        SOCK_STREAM
        SO_SNDBUF(16384),SO_RCVBUF(5120)
        sockname: AF_UNIX 
        peer: sshd[3597] zone: global[0]
   1: S_IFSOCK mode:0666 dev:532,0 ino:5812 uid:0 gid:0 rdev:0,0
      O_RDWR
        SOCK_STREAM
        SO_SNDBUF(16384),SO_RCVBUF(5120)
        sockname: AF_UNIX 
        peer: sshd[3597] zone: global[0]
   2: S_IFSOCK mode:0666 dev:532,0 ino:5812 uid:0 gid:0 rdev:0,0
      O_RDWR
        SOCK_STREAM
        SO_SNDBUF(16384),SO_RCVBUF(5120)
        sockname: AF_UNIX 
        peer: sshd[3597] zone: global[0]
   3: S_IFIFO mode:0000 dev:521,0 ino:3278 uid:0 gid:0 rdev:0,0
      O_RDWR

client side:
root@x4275-1-4-35:/export/d# ptree 11572
6278  screen
  6279  /usr/bin/bash
    11572 /opt/niksula/perl5/bin/perl /opt/niksula/bin/znapzend --connectTimeou
      11585 /opt/niksula/perl5/bin/perl /opt/niksula/bin/znapzend --connectTime
        11588 sh -c zfs send -I zpool1/tech-0@2015-05-15-172248 zpool1/tech-0@2
          11589 zfs send -I zpool1/tech-0@2015-05-15-172248 zpool1/tech-0@2015-
          11590 ssh -o Compression=yes -o CompressionLevel=1 -o batchMode=yes -

I've done a previous mbuffer over the WAN and was getting 70MB/sec on a snapshot transfer. Since this is a few GB of stuff at 1MB/sec, it's taking a long while.

**Comment by hadfl** [comment]
from the `znapzendzetup` man page:
```
--mbuffer=/usr/bin/mbuffer:31337

Specifiy the path to your copy of the mbuffer utility and the port used on the destination.
Caution: znapzend will send the data directly from source mbuffer to destination mbuffer,
thus data stream is not encrypted.
```
if you specify a `port`, there will be mbuffer -> mbuffer data traffic. if you omit the port, data will go through ssh.

**Comment by DougHughes** [comment]
Huh, I swear I had this setup, but sure enough the znapzendzetup doesn't 
show it. I don't know how I missed it. Trying to confirm this now. Thanks.
