### ISSUE TITLE
--loglevel not behaving as expected

### ISSUE THREAD

**Issue by DougHughes** [oetiker/znapzend#148]
Shouldn't this not print debug and info stuff to output/error?
# znapzend  --connectTimeout=10 --runonce=zpool1/tech-0 --loglevel=warning

[Sun May 17 21:18:50 2015] [info] refreshing backup plans...
[Sun May 17 21:18:52 2015] [info] found a valid backup plan for zpool1/tech-0...
[Sun May 17 21:18:52 2015] [debug] snapshot worker for zpool1/tech-0 spawned (14664)
[Sun May 17 21:18:52 2015] [info] running pre snapshot command on zpool1/tech-0
[Sun May 17 21:18:52 2015] [info] creating snapshot on zpool1/tech-0
[Sun May 17 21:18:52 2015] [info] running post snapshot command on zpool1/tech-0
[Sun May 17 21:18:52 2015] [debug] snapshot worker for zpool1/tech-0 done (14664)
[Sun May 17 21:18:52 2015] [debug] send/receive worker for zpool1/tech-0 spawned (14670)
[Sun May 17 21:18:52 2015] [info] starting work on backupSet zpool1/tech-0
[Sun May 17 21:18:52 2015] [debug] starting work on dst a
[Sun May 17 21:18:52 2015] [debug] sending snapshots from zpool1/tech-0 to root@x4275-3-15-20:zpool1/tech-0
[Sun May 17 21:18:53 2015] [debug] receive process on x4275-3-15-20 spawned (14673)

**Comment by hadfl** [comment]
fixed: https://github.com/oetiker/znapzend/pull/149

thanks for reporting!
