### ISSUE TITLE
two way replication with mbuffer

### ISSUE THREAD

**Issue by expertaz-zz** [oetiker/znapzend#150]
Hello,

I'm running one way mbuffer replication with success,

anyway doing two way replication with znapzend?

Like this:
Node1 has source1 and dest2(rep from Node2) filesystems,Node2 has dest1(rep from Node1) and source2 filesystems

node1 source1  to node2 dest1 

node2 source2 to node1 dest2 

Thanks

**Comment by oetiker** [comment]
could you please ask your questions on http://serverfault.com/ and tag them with `znapzend`
