### ISSUE TITLE
znapzend with mbuffer, remote exits and hangs the sender

### ISSUE THREAD

**Issue by rjeschmi** [oetiker/znapzend#151]
The tree looks something like this

``` sh
 4186 ?        Ss     0:00 /software/tools/packages/plenv/versions/5.18.2/bin/perl /software/packages/znapzend-0.14.0/bin/znapzend
 4840 ?        S      0:00  \_ /software/tools/packages/plenv/versions/5.18.2/bin/perl /software/packages/znapzend-0.14.0/bin/znapzend
 7973 ?        Z      0:00      \_ [znapzend] <defunct>
 7999 ?        S      0:00      \_ sh -c zfs send -I bioinfo2/backup@2015-05-23-000000 bioinfo2/backup@2015-05-27-084500|/software/packages/mbuffer-20150412/bin/mbuffer -q -s 128k -W 60 -m 1G -O '192.168.170.8:9
 8001 ?        Sl    19:01          \_ /software/packages/mbuffer-20150412/bin/mbuffer -q -s 128k -W 60 -m 1G -O 192.168.170.8:9092
```

**Comment by rjeschmi** [comment]
At this point mbuffer has gone to 100% cpu and znapzend hasn't noticed that the other end has hung up.

**Comment by hadfl** [comment]
is there enough free memory on your system so the 1GB mbuffer can be allocated within a reasonable amount of time? we have regularely seen issues from different users on systems with 'large' mbuffer settings. you could try to decrease it to 256MB for testing.

**Comment by rjeschmi** [comment]
That sounds reasonable, thanks. I have 8GB of RAM, but there does seem to be some pressure when running the recv.

I figured I'd point it out, since it doesn't seem to die very gracefully in this case. The ssh session seems to have died, but znapzend doesn't catch that for whatever reason and mbuffer just spins.

**Comment by rjeschmi** [comment]
thanks @hadfl, the memory tip helped my immediate problem.

Is it worthwhile leaving this issue to track a feature request, or should we do it some other way?
