### ISSUE TITLE
anyway doing this senario with znapzend?

### ISSUE THREAD

**Issue by expertaz-zz** [oetiker/znapzend#152]
I could not send attached pic to serverfault because of reputation limit.

anyway doing reverse replication from slave to master as described in photo
![reverserepli](https://cloud.githubusercontent.com/assets/9352054/7932326/239ee1d8-0920-11e5-8c6a-50ce691fc3a3.JPG)

**Comment by oetiker** [comment]
well ... znapzend does not replicate its  own configuration, so theoretically, you can have a separate znapzend configuration on the destination target, BUT there is no provision for preventing the syncing going in both directions at once which would not be ideal, so I guess some extra safeguards would have to be put in place to make such a scenario work.

**Comment by expertaz** [comment]
Tobi in my case ,I want one time reverse replication from destination  to source (only changed blocks since  last successful replication from source to destination,not all data) even manually,is it possible?

**Comment by oetiker** [comment]
I understand your scenario ... it is certainly possible ... as I said, the problem is to make absolutely sure that things run in the right direction ... imagine, znapzend on 'source' starts running again before you have managed to sync back ... then all your changes on destination will be cleared away.

**Comment by expertaz** [comment]
ok,could you make adaptation of znapzend for   this senario as a customization?and how much will it cost?

**Comment by oetiker** [comment]
:+1: we'll look into this and let you know

**Comment by oetiker** [comment]
it will probably be a few weeks before we can tell you something as @hadfl is currently in a major rewrite of znapzend.

**Comment by expertaz** [comment]
maybe zrep script code will help you about this senario,as I know zrep has failover and takeoker  features.

**Comment by oetiker** [comment]
our current idea is that the normal znapzend script would detect that you have modified files on the destinaton device and stop sending new snapshots there but complain loudly. You would then start znapzend in interactive mode on the source and get it to sync the changes from dest back to source. I guess the implementation of such a feature would be in the range of a few thousand dollar.

**Comment by expertaz** [comment]
ok, thank you for info,
please keep in mind,zvol  wiil not receive replication if its shared(***cannot receive new filesystem stream: dataset is busy),maybe znapzend will control destination  ,if its zvol(volume) and shared then first will unshare it and then start send replication.

as I understand znapzend will run on source node only and will coordinate these tasks from source,it's better than running znapzend on all nodes,less complex.

**Comment by oetiker** [comment]
yes that is the idea ... as for syncing back volumes, there merging is not realistic I guess it is all or nothing really, so the volume must not be shared prior to backsync, since otherwise is would basically imply it is in active use ...

**Comment by expertaz** [comment]
I misunderstood few thousand  with few hundreds sorry:((my max budget 500$ for this customization,sorry again

**Comment by aaltonenp** [comment]
This would be a wonderful feature. Maybe you could setup a donation pool for features like this one?
