### ISSUE TITLE
Maintenance state with svcadm and Oracle 11.2

### ISSUE THREAD

**Issue by spiro-stathakis** [oetiker/znapzend#157]
Hi there, 
Since upgrading to Oracle 11.2 from 11.1 znapzend (pre built) goes into maintenance state with the following message: "Restarting too quickly, changing state to maintenance."

**Comment by oetiker** [comment]
can you start it by hand to see what it is unhappy about ?

**Comment by spiro-stathakis** [comment]
Thank you Tobias,

It seems ok on start but it went into maintenance state if DST:a or DST:b
is down.

**Comment by oetiker** [comment]
was there any error message in syslog ?

**Comment by spiro-stathakis** [comment]
There is this message:

``` log
Mojo::Reactor::Poll: Read failed: Event "close" failed:  at /opt/znapzend-0.14.0/bin/../lib/ZnapZend/ZFS.pm line 380
```
