### ISSUE TITLE
Znapzend doesn't create ZFS bookmarks accompanying the ZFS Snapshots

### ISSUE THREAD

**Issue by JMoVS** [oetiker/znapzend#160]
As discussed here: https://serverfault.com/questions/714238/is-it-possible-to-use-bookmarks-with-znapzend?noredirect=1#,

for use cases where the destination isn't always available, it is a cheap and sensible thing to do (probably) to create bookmarks along the snapshots to be able to make incremental backups after extended periods of time even though no common snapshot between source and target exists.

I'll have a look into code (whether I can wrap my head around) and report back

**Comment by JMoVS** [comment]
How is this roughly structured and where are the commands to be executed generated?

**Comment by oetiker** [comment]
I guess you would want to look at lib/ZnapZend/ZFS.pm

**Comment by JMoVS** [comment]
I looked into it. But to be honest, my experience with PERL is rather limited. I had a closer look at the createSnapshot method but I didn't figure out what the "qw" is doing? Is that a short-word for "execute on the command line"?

And in general, do you think this should (at least in ZFS.pm) be its own method (createBookmark) or should it be included in createSnapshot or called from there? It could be a config option whether one wants to use them (but there seemingly is no real downside, so I don't know).

**Comment by oetiker** [comment]
qw = quote word

qw(a b c) equals "a","b","c"

creating a bookmark for each snapshot ? I have not played with bookmarks yet, but it does seem sensible ...

although, in the longrun someone will thave to clenup the bookmarks too I guess

maybe the best thing would be to use bookmarks exclusively on the source side and offer source snapshoting as an independent feature.

actually, bookmarks on the source side could probably be configured automatically by looking at the needs od the destinatiin schedules.

does oracle zfs also have bookmarks?

**Comment by JMoVS** [comment]
hmm ok.

Yes, I would create a bookmark for every snapshot as the storage needs are miniscule (they don't take up the space a snapshot would need). They should, I agree, be cleaned up but I have to do some tests to see how much space they actually need. I haven't done that yet.

The bookmarks are a source only thing as they aren't sent and can't be used as a target, it's merely for the purpose of no common snapshot but still wanting to do an incremental backup.

> actually, bookmarks on the source side could probably be configured automatically by looking at the needs od the destinatiin schedules.

What exactly do you mean? I can in this respect only think of reasonable defaults that can be auto-generated, but not more.

As far as I know not, because they are a feature-flag of OpenZFS http://www.open-zfs.org/wiki/Feature_Flags

**Comment by oetiker** [comment]
since bookamarks take very little space, we can keep much more of them ... actually we could configure them by looking at the highest resolution for snapshots to be stored on the desitnation ... 

or another option would be that add a bookmark for every snapshot that is about to be removed at the source side ... this still does not resolve the cleanup issue, but I guess that could be configured pretty straight forward by just specifying a maximum age for the bookmarks, as this would define for how long the destination would be able to re-sync with the source

**Comment by JMoVS** [comment]
yes, exactly. I am not experienced in programming PERL and am wondering how I would go about starting the implementation of this. DO you have any ideas on how to proceed here?

**Comment by JMoVS** [comment]
any news on that? I've seen that this is probably potentially related to #144 from @rottegift . Any news on that? ;-)
