### ISSUE TITLE
ZnapZend doesn't work on pools with upper case letters as created property would contain upper case letters

### ISSUE THREAD

**Issue by JMoVS** [oetiker/znapzend#162]
I have a pool which has a mixed-case name (ZFSPower) and I tried to setup znapzend. Now the problem is that the auto-generated property it wants to assign to the datasets will contain upper-case letters and upper-case letters are not allowed in properties.

Specific error message I get is:
```cannot set property for 'ZFSPower': invalid property 'org.znapzend:dst_ZFSSnaps_plan```

```ERROR: could not set property dst_ZFSSnaps_plan on ZFSPower```

**Comment by rottegift** [comment]
The tag for DST key does not have to match any actual dataset.  You can use [a-z] or [0-9] for instance.  It will default to 0 if unspecified (see $key variable in bin/znapzend).

```
znapzend create SRC '1hour=>1week' FOO/Bar DST:a '1hour=>1week,1day=>1month' Backups/from_Foo/Bar
```

**Comment by JMoVS** [comment]
I quickly whipped up a pull request to note that in the docu of the znapzendsetup utility, what do you think?
