### ISSUE TITLE
znapzend replication between sites over vpn

### ISSUE THREAD

**Issue by expertaz-zz** [oetiker/znapzend#165]
Planning to use znapzend between 2 sites connectted over 5Mbps/5Mbps VPN.

Source data(Site A) is about 2 TB, Anyway to do first znapzend replication to locally attached disks pool(DST.B) in Site A and then export DST.B pool and attach them Site B Omnios and start incremental znapzend replication from Site A to Site B again?

**Comment by moetiker** [comment]
sound like a good idea.

**Comment by expertaz** [comment]
Manuel  will incremental snapshot shipping continue after export import operation ?or znapzend will start full snapshot shipping again?
