### ISSUE TITLE
remote_dst and Sudo

### ISSUE THREAD

**Issue by jhetrick** [oetiker/znapzend#166]
Maybe I'm misunderstanding --sudo option.

I've got a pair of linux systems and I'm wishing to use a locked down account with only zfs commands on the receiver.  Eg: the only thing the user on the receiver can do is run zfs <cmd>, and the sender execs with sudo.

znapzendzetup create --sudo --tsformat='%Y-%m-%d-%H%M%S-to-linuxzfshost' SRC '30minutes=>5minutes' dpool01/joetest2 DST:linuxzfshost '30minutes=>5minutes,1d=>4h' joetestbak@dpool01-joetest2:dpool01/Backups/zfs/fs/dpool01/joetest2

If let daemonized znapzend run, it complains about the destination filesystem not existing; so I decided to debug with runonce:

Initially problems with .bashrc and paths; those should be solved, but it appears that sudo is not being exec'd against "zfs" below with the "failed to load ZFS module stack", which is what happens when one tries to exec zfs or zpool as a non-root user.

What am I doing incorrectly; does one need to _also_ run znapzend with the --features=sudo option for this to work (thus configuring the users on both local and remote systems, as well as sudo?

/opt/znapzend-0.14.0/bin/znapzend --debug --runonce=dpool01/joetest2
[Wed Sep  9 12:14:33 2015] [info] refreshing backup plans...
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
# ssh -o Compression=yes -o CompressionLevel=1 -o Cipher=arcfour -o batchMode=yes -o ConnectTimeout=30 joetestbak@dpool01-joetest2 zfs list -H -o name -t 'filesystem,volume' 'dpool01/Backups/zfs/fs/dpool01/joetest2'

Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
[Wed Sep  9 12:14:33 2015] [warn] destination 'joetestbak@dpool01-joetest2:dpool01/Backups/zfs/fs/dpool01/joetest2' does not exist or is offline. will be rechecked every run...
[Wed Sep  9 12:14:33 2015] [info] found a valid backup plan for dpool01/joetest2...
[Wed Sep  9 12:14:33 2015] [debug] snapshot worker for dpool01/joetest2 spawned (20762)
[Wed Sep  9 12:14:33 2015] [info] creating snapshot on dpool01/joetest2
# zfs snapshot dpool01/joetest2@2015-09-09-121433-to-linuxzfshost

[Wed Sep  9 12:14:33 2015] [debug] snapshot worker for dpool01/joetest2 done (20762)
[Wed Sep  9 12:14:33 2015] [debug] send/receive worker for dpool01/joetest2 spawned (20764)
[Wed Sep  9 12:14:33 2015] [info] starting work on backupSet dpool01/joetest2
# ssh -o Compression=yes -o CompressionLevel=1 -o Cipher=arcfour -o batchMode=yes -o ConnectTimeout=30 joetestbak@dpool01-joetest2 zfs list -H -o name -t 'filesystem,volume' 'dpool01/Backups/zfs/fs/dpool01/joetest2'

Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
[Wed Sep  9 12:14:33 2015] [warn] destination 'joetestbak@dpool01-joetest2:dpool01/Backups/zfs/fs/dpool01/joetest2' does not exist or is offline. ignoring it for this round...
# zfs list -H -o name -t snapshot -s creation -d 1 dpool01/joetest2

[Wed Sep  9 12:14:33 2015] [debug] cleaning up snapshots on dpool01/joetest2
# zfs destroy dpool01/joetest2@2015-09-09-121338-to-linuxzfshost

[Wed Sep  9 12:14:33 2015] [info] done with backupset dpool01/joetest2 in 0 seconds
[Wed Sep  9 12:14:33 2015] [debug] send/receive worker for dpool01/joetest2 done (20764)

**Comment by grueni** [comment]
This is the start method of our script running in Solaris 11.2
I guess you should use "--features=sudo".

start() {
	sudo -u $APPUSER $APP --features=oracleMode,recvu,pfexec --logto=$LOGFILE --loglevel=info --daemonize --pidfile=$PIDFILE
	return 0
}

**Comment by jhetrick** [comment]
Thanks;

	I think I was wanting it to work differently than it does; which is OK.  We have an existing zfs-replication structure (deployed and managed via puppet) and I was trying to closely replicate that.  Basically the sender/receiver are unpriv/non-root accounts (controlled via ZFS ACL) with keys.  But they're different accounts for each replicated filesystem.

  We're rolling znapzend out to manage ZFSoL infrastructure, primarily, and the expected way is for the sender to be a priv (root or sudo) account, but not per-filesystem; which is OK, we've been working that into our deploy.  It just required me to adjust my thinking :)

J

On 16 Dec 06:03, grueni wrote:
> This is the start method of our script running in Solaris 11.2
> I guess you should use "--features=sudo".
> 
> start() {
> 	sudo -u $APPUSER $APP --features=oracleMode,recvu,pfexec --logto=$LOGFILE --loglevel=info --daemonize --pidfile=$PIDFILE
> 	return 0
> }
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/oetiker/znapzend/issues/166#issuecomment-165114175

-- 
Joe Hetrick
perl -e 'print pack(h*,a6865647279636b604269647a616e69647f627e2e65647a0)'
BOFH Excuse: root rot
