### ISSUE TITLE
Existing snapshots at the source stop worker/znapzend snapshots? (without creating debug output?)

### ISSUE THREAD

**Issue by xlwoon** [oetiker/znapzend#167]
Hello,

I'm running a fairly simple plan to back up a filesystem on one server to the other with the same policy

root@de001fs055:~/
# >/opt/znapzend-0.14.0/bin/znapzendzetup create --recursive --mbuffer=/opt/csw/bin/mbuffer --mbuffersize=1G --tsformat='%Y-%m-%d_%H:%M:%S' SRC '7days=>1hour,30days=>4hours,90days=>1day' store/projects DST:a '7days=>1hour,30days=>4hours,90days=>1day' root@de001bs033:store/projects

**\* backup plan: store/projects ***
dst_a           = root@de001bs033:store/projects
dst_a_plan      = 7days=>1hour,30days=>4hours,90days=>1day
enabled         = on
mbuffer         = /opt/csw/bin/mbuffer
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = off
recursive       = on
src             = store/projects
src_plan        = 7days=>1hour,30days=>4hours,90days=>1day
tsformat        = %Y-%m-%d_%H:%M:%S

Do you want to save this backup set [y/N]? y
root@de001fs055:~/
# >svcadm restart /oep/znapzend
## I'm running znapzend as a service, so after I restart it, I see, in znapzend.log:

[Fri Sep 11 11:38:28 2015] [info] terminating znapzend...
[Fri Sep 11 11:38:30 2015] [info] refreshing backup plans...
[Fri Sep 11 11:38:37 2015] [info] found a valid backup plan for store/projects...
## but nothing further.

Older snapshots exist at the source, and no snapshots exist yet at the destination (we are in the process of migrating from an old, buggy in-house snapshot tool to znapzend).
I tested znapzend to be tolerant of non-znapzend snapshots in the source filesystem, but now that I recall, I created them after znapzend started working.

Is it possible that the existing snapshots are stopping znapzend from starting any work at the source at all? Is  there a way I can override this, while preserving my old snapshots?

**Comment by xlwoon** [comment]
Ah, I'm really sorry for starting the ticket, it seems I made a silly mistake -- might be obvious from here (:
I'll leave this open just a bit longer, and I'll close it when I'm sure I have no issues

**Comment by oetiker** [comment]
no existing snapshots do not stop znapzend from working ... 

you may want to run in in debug mode o get started ...
