### ISSUE TITLE
znapzend doesn't seem to recover when mbuffer has receive error

### ISSUE THREAD

**Issue by DougHughes** [oetiker/znapzend#169]
Admittedly, this is an mbuffer error at root as evidenced by this:
16244/2:        write(3, 0xFFFFFFFFF91331D7, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D6, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D5, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D4, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D3, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D2, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D1, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331D0, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CF, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CE, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CD, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CC, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CB, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331CA, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C9, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C8, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C7, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C6, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C5, 131072)            Err#32 EPIPE
16244/2:        write(3, 0xFFFFFFFFF91331C4, 131072)            Err#32 EPIPE
^C16244/2:      write(3, 0xFFFFFFFFF91331C3, 131072)            Err#32 EPIPE

the zfs read seems to have aborted for some reason (unknown as of yet. I'm trying to discover the filesystem but that is difficult since there are many in this state) and the mbuffer process (16244) is busily trying to write to the pipe but there's nothing there and it keeps getting back the EPIPE but doesn't do anything. So I have a few dozen of these on the receiver, but there doesn't seem to be any recovery from this state. They just build up on the client and server side, but I can't figure out for which filesystems (yet)

**Comment by DougHughes** [comment]
I have more color here.. When there are *lots* of filesystems (158) in daemon mode, and all of these sshs try to run at the same time at the top of the hour, many of them start failing. in sequential mode, one per filesystem, everything works great, but all at once is havoc.

The output looks kind of like this:
mbuffer: warning: error connecting to thumper1:4044: Connection refused
mbuffer: error: unable to connect to thumper1:4044
mbuffer: fatal: no output left - nothing to do
internal error: Broken pipe
mbuffer: warning: error connecting to thumper1:4072: Connection refused
mbuffer: error: unable to connect to thumper1:4072
mbuffer: fatal: no output left - nothing to do
internal error: Broken pipe
# ssh -o Compression=yes -o CompressionLevel=1 -o Cipher=arcfour -o batchMode=yes -o ConnectTimeout=500 root@thumper1 zfs list -H -o name -t snapshot -s creation -d 1 zpool1/backup/d/stanwang-0
mbuffer: warning: error connecting to thumper1:4060: Connection refused
mbuffer: error: unable to connect to thumper1:4060
mbuffer: fatal: no output left - nothing to do
warning: cannot send 'zpool1/d/gregerse-0@2015-09-29-000000': Broken pipe
internal error: Broken pipe
# zfs list -H -o name -t snapshot -s creation -d 1 zpool1/d/cariannc-0
mbuffer: warning: error connecting to thumper1:4103: Connection refused
mbuffer: error: unable to connect to thumper1:4103
mbuffer: fatal: no output left - nothing to do
internal error: Broken pipe
# zfs destroy zpool1/d/cariannc-0@2015-09-26-230000
mbuffer: warning: error connecting to thumper1:4001: Connection refused
mbuffer: error: unable to connect to thumper1:4001

But, some sshd processes with shell forks are left on the server:
    root  3099     1   0 00:00:25 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4082|zfs recv -F zpool1/ba
    root 10443     1   0   Sep 26 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4123|zfs recv -F zpool1/ba
    root 10960     1   0   Sep 26 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4167|zfs recv -F zpool1/ba
    root 10964     1   0   Sep 26 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4156|zfs recv -F zpool1/ba
    root 10940     1   0   Sep 26 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4038|zfs recv -F zpool1/ba
    root 11650     1   0   Sep 26 ?           0:00 bash -c /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4016|zfs recv -F zpool1/ba


and snapshots are created on the primary that are not created on the receiver, which makes things out of sync and manual intervention is required to clean things up.

What I think needs to happen (among other things, perhaps)
1) have to check to see if the client side mbuffer connection succeeds or fails. If it fails, delete the snapshot on the primary/client side. Same if the ssh fails for other reasons, delete the primary side snapshot, or manual intervention is required to delete it anyway because now the primary and the secondary are out of synch.
2) I'm still trying to track down the exact sequence of errors and a possible solution using a lot of truss, but I'm not there quite yet. I'm not seeing anythign obvious of a truss of the sshd process on the server side, other than I definitely do *not* see mbuffer processes that bind the ports described above. (when it says connection refused, there's no indication of an mbuffer on the receiver side that gets launched that binds to that port)

**Comment by oetiker** [comment]
it should not matter if a snapshot does not get transferred, it would be transferred in the next round ... what makes you say that manual intervention is required ?

**Comment by DougHughes** [comment]
I was getting an error, but let me confirm it with respect to primary
having more recent. Maybe it was just an ignoreable warning and I'm
overreacting, but there's definitely still some sort of
timing/overload/cleanup thing that I'm tracking dowin with leftover
processes on the receiver side and things not connecting.

**Comment by oetiker** [comment]
if mbuffer on the receiver side does not die, this is certainly a problem as it will occupy the port ... but the snapshots already generated on the sender side will NOT be an issue.

**Comment by DougHughes** [comment]
It's not mbuffer not dieing. mbuffer appears to never get started, it's the
bash above mbuffer that's left lingering around with an sshd.

Like so (no mbuffer processes though, and no zfs processes)
[[root@thumper1 16:57:06 / 134]]$ ps -ef | grep zfs
    root  3099     1   0 00:00:25 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4082|zfs recv -F zpool1/ba
    root 10443     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4123|zfs recv -F zpool1/ba
    root 10960     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4167|zfs recv -F zpool1/ba
    root 10964     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4156|zfs recv -F zpool1/ba
    root 10940     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4038|zfs recv -F zpool1/ba
    root 11650     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4016|zfs recv -F zpool1/ba
    root 11838     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4085|zfs recv -F zpool1/ba
    root 12168     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4032|zfs recv -F zpool1/ba
    root 12214     1   0   Sep 26 ?           0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4147|zfs recv -F zpool1/ba

There's another running right now (just turned top of the hour) with truss
on both sides so hopefully I can cross-reference things.
I'm still plugging at it as time allows amidst other tasks, but if you have
anything specific you'd like me to collect or look at or other ideas, shoot
them my way. I assume I'll see you at LISA in DC in a about 5 weeks?

**Comment by DougHughes** [comment]
hrm, no, I contradicted my earlier post above and that was incorrect. There
are in fact mbuffers hanging aroudn on the receiver, but the mbuffers that
are hanging aroudn do not match the repeating/loopint attempts on the
sender to try to finish it's hourly job (it keeps trying repeatedly for
those that fail, which is arguably the right thing to do)

[[root@thumper1 11:08:49 / 152]]$ /usr/ucb/ps -auxww | grep mbuffer
root     21658 10.3  0.013224 2196 ?        O 11:00:41  1:45
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4167
root     14447 10.3  0.013224 2236 ?        O 11:00:07  1:41
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4022
root     19285 10.3  0.013224 2236 ?        O 11:00:28  1:40
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4166
root     19893 10.3  0.013224 2216 ?        O 11:00:31  1:40
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4147
root     19202 10.3  0.013224 2232 ?        O 11:00:28  1:39
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4146
root     17014 10.3  0.013224 2232 ?        O 11:00:17  1:39
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4097
root     15191 10.3  0.11322411912 ?        O 11:00:09  1:38
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4003
root      2496  0.0  0.0 1428  804 pts/1    S 11:08:53  0:00 grep mbuffer
root     14427  0.0  0.0 2840 1700 ?        S 11:00:07  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4022|zfs recv -F
zpool1/backup/d/cioffari-0
root     15185  0.0  0.0 2840 1700 ?        S 11:00:09  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4003|zfs recv -F
zpool1/backup/d/antonlogs
root     17005  0.0  0.0 2840 1700 ?        S 11:00:17  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4097|zfs recv -F
zpool1/backup/d/lij-0
root     19191  0.0  0.0 2840 1700 ?        S 11:00:28  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4146|zfs recv -F
zpool1/backup/d/singhsn-0
root     19273  0.0  0.0 2840 1700 ?        S 11:00:28  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4166|zfs recv -F
zpool1/backup/d/weinreic-0
root     19880  0.0  0.0 2840 1700 ?        S 11:00:31  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4147|zfs recv -F
zpool1/backup/d/skopp-0
root     21648  0.0  0.0 2840 1700 ?        S 11:00:41  0:00 bash -c
/opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4167|zfs recv -F
zpool1/backup/d/white-0
[[root@thumper1 11:08:53 / 153]]$

But on the sender, the port listings for those things that it's retrying do
not overlap:
internal error: Broken pipe
mbuffer: warning: error connecting to thumper1:4174: Connection refused
mbuffer: error: unable to connect to thumper1:4174
mbuffer: fatal: no output left - nothing to do
internal error: Broken pipe
mbuffer: warning: error connecting to thumper1:4004: Connection refused
mbuffer: error: unable to connect to thumper1:4004
mbuffer: fatal: no output left - nothing to do
mbuffer: warning: error connecting to thumper1:4010: Connection refused
mbuffer: error: unable to connect to thumper1:4010
mbuffer: fatal: no output left - nothing to do
warning: cannot send 'zpool1/d/batsonb-0@2015-09-30-110000': Broken pipe
internal error: Broken pipe
mbuffer: warning: error connecting to thumper1:4154: Connection refused
mbuffer: error: unable to connect to thumper1:4154
mbuffer: fatal: no output left - nothing to do
mbuffer: warning: error connecting to thumper1:4038: Connection refused
mbuffer: error: unable to connect to thumper1:4038
mbuffer: fatal: no output left - nothing to do
warning: cannot send 'zpool1/d/drdcon8-0@2015-09-30-110000': Broken pipe
internal error: Broken pipe
mbuffer: warning: error connecting to thumper1:4071: Connection refused
mbuffer: error: unable to connect to thumper1:4071
mbuffer: fatal: no output left - nothing to do
<more>

The sender side keeps showing 4071 for instance, but in the truss output on
the receiver, there's no mbuffer being started to bind 4071.

The sender is clearly looping over and trying send/mbuffer:
28622:    zfs send -I zpool1/d/hunt-0@2015-09-28-220000
zpool1/d/hunt-0@2015-09-30-110000|/opt/csw/bin/mbuffer -q -s 128k -m 10M -O
'thumper1:4071'
28626:   argv: zfs send -I zpool1/d/hunt-0@2015-09-28-220000
28626:    zpool1/d/hunt-0@2015-09-30-110000
28767:    zfs send -I zpool1/d/hunt-0@2015-09-28-220000
zpool1/d/hunt-0@2015-09-30-110000|/opt/csw/bin/mbuffer -q -s 128k -m 10M -O
'thumper1:4071'
28771:   argv: zfs send -I zpool1/d/hunt-0@2015-09-28-220000
28771:    zpool1/d/hunt-0@2015-09-30-110000
28911:    zfs send -I zpool1/d/hunt-0@2015-09-28-220000
zpool1/d/hunt-0@2015-09-30-110000|/opt/csw/bin/mbuffer -q -s 128k -m 10M -O
'thumper1:4071'
28915:   argv: zfs send -I zpool1/d/hunt-0@2015-09-28-220000
28915:    zpool1/d/hunt-0@2015-09-30-110000
29055:    zfs send -I zpool1/d/hunt-0@2015-09-28-220000
zpool1/d/hunt-0@2015-09-30-110000|/opt/csw/bin/mbuffer -q -s 128k -m 10M -O
'thumper1:4071'
29059:   argv: zfs send -I zpool1/d/hunt-0@2015-09-28-220000
29059:    zpool1/d/hunt-0@2015-09-30-110000
29200:    zfs send -I zpool1/d/hunt-0@2015-09-28-220000
zpool1/d/hunt-0@2015-09-30-110000|/opt/csw/bin/mbuffer -q -s 128k -m 10M -O
'thumper1:4071'
29204:   argv: zfs send -I zpool1/d/hunt-0@2015-09-28-220000
29204:    zpool1/d/hunt-0@2015-09-30-110000

Going back to the beginning, the first attempt from the sender to
connect/span is in process 5410:
(all the zfs list precursor stuff seems to work ok)
but 5410 exits with a 255 early on.
...
5410:   1934.7021        0.0000
getuid()
= 0 [0]
5410:   1934.7021        0.0000
getuid()
= 0 [0]
5410:   1934.7022        0.0000
getgid()
= 0 [0]
5410:   1934.7022        0.0000
getgid()
= 0 [0]
5410:   1934.7024        0.0000 ioctl(2, TCGETA,
0x08047BDC)
= 0
5410:   1934.7024        0.0000 ioctl(-1, TCGETA,
0x08047BDC)
Err#9 EBADF
5410:   1934.7025        0.0000
getuid()
= 0 [0]
5410:   1934.7025        0.0000 stat64("/usr/bin/ssh",
0x08047AB0)
= 0
5410:   1934.7026        0.0000 access("/usr/bin/ssh",
X_OK|E_OK)
= 0
5410:   1934.7026        0.0000
brk(0x080775C0)
= 0
5410:   1934.7046        0.0002
fork1()
= 5416
...
5416:   1934.7344        0.0000 read(4, " s s h - d s s   A A A A"..,
1024)     = 618
5416:   1934.7347        0.0000 llseek(4, 0,
SEEK_CUR)                          = 618
5416:   1934.7347        0.0000
close(4)                                        = 0
5416:   1934.7348        0.0000
getuid()                                        = 0 [0]
5416:   1934.7348        0.0000
getuid()                                        = 0 [0]
5416:   1934.7348        0.0000 open64("/var/run/name_service_door",
O_RDONLY)  Err#2 ENOENT
5416:   1934.7349        0.0000 open("/etc/passwd",
O_RDONLY|O_LARGEFILE)       = 4
5416:   1934.7349        0.0000 fstat64(4,
0x080471C0)                          = 0
5416:   1934.7350        0.0000 fcntl(4, F_DUPFD,
0x00000100)                   Err#22 EINVAL
5416:   1934.7351        0.0000 read(4, " r o o t : x : 0 : 0 : S"..,
1024)     = 1024
5416:   1934.7351        0.0000
close(4)                                        = 0
5416:   1934.7352        0.0000
getuid()                                        = 0 [0]
5416:   1934.7353        0.0000
getuid()                                        = 0 [0]
5416:   1934.7354        0.0000 open64("/var/run/name_service_door",
O_RDONLY)  Err#2 ENOENT
5416:   1934.7354        0.0000 open("/etc/passwd",
O_RDONLY|O_LARGEFILE)       = 4
5416:   1934.7355        0.0000 fstat64(4,
0x080471C0)                          = 0
5416:   1934.7355        0.0000 fcntl(4, F_DUPFD,
0x00000100)                   Err#22 EINVAL
5416:   1934.7356        0.0000 read(4, " r o o t : x : 0 : 0 : S"..,
1024)     = 1024
5416:   1934.7356        0.0000
close(4)                                        = 0
5416:   1934.7357        0.0000
schedctl()                                      = 0xFEFEC000
5416:   1934.7357        0.0000 sigaction(SIGPIPE, 0x08047990,
0x08047A10)      = 0
5416:   1934.9084        0.0000 read(3, 0x08047808,
1)                          = 0
5416:   1934.9091        0.0000 fstat64(2,
0x08046290)                          = 0
5416:   1934.9091        0.0000 write(2, 0x080473DC,
61)                        = 61
5416:      s s h _ e x c h a n g e _ i d e n t i f i c a t i o n :   C o n
5416:      n e c t i o n   c l o s e d   b y   r e m o t e   h o s t
5416:   1934.9093        0.0000 write(2, "\r\n",
2)                             = 2
5416:   1934.9093        0.0000 shutdown(3, SHUT_RDWR,
SOV_DEFAULT)             = 0
5416:   1934.9094        0.0000
close(3)                                        = 0
5416:   1934.9096        0.0000 _exit(255)
...
5410:   1934.7084        0.0000 lwp_sigmask(SIG_SETMASK, 0x00000000,
0x00000000)
 = 0xFFBFFEFF [0x0000FFFF]
5410:   1934.9196        0.0000 waitid(P_PID, 5416, 0x08047AE0,
WEXITED|WTRAPPED
|WNOWAIT) = 0
5410:   1934.9197        0.0000 ioctl(0, TIOCGPGRP,
0x08047B50)
= 0
5410:   1934.9197        0.0000 ioctl(0, TCGETS,
0x08075ED0)
= 0
5410:   1934.9198        0.0000 waitid(P_PID, 5416, 0x08047AE0,
WEXITED|WTRAPPED
) = 0
5410:   1934.9199        0.0000
brk(0x080773C0)
= 0
5410:   1934.9312        0.0000 _exit(255)

so the remote mbuffer doesn't get to start,

unfortunately, I didn't add -v connect or -v getpeername so I can't
correlate the send/receive port pair to the destination with 100% accuracy,
but I can zoom in on the time range on the receiving sshd to find the
accept.

Theory: the exit code of the remote spawned mbuffer isn't caught at the
sender side, and the sender just goes into it's send/mbuffer loop without
checking that its remote side isn't there to receive anything. ?

adding -v getpeername to get the ports for easier cross-reference

**Comment by DougHughes** [comment]
boiled stuff down with lots of grepping and sedding:

client:

23232:    ssh -o Compression=yes -o CompressionLevel=1 -o Cipher=arcfour -o batc
hMode=yes -o ConnectTimeout=500 root@thumper1 '/opt/csw/bin/mbuffer -q -s 128k -
m 10M -4 -I 4048|zfs recv -F zpool1/backup/d/feher-0'
23135:  3458.6564        0.0000 _exit(0)
23239:    /opt/csw/bin/mbuffer -q -s 128k -m 10M -4 -I 4048|zfs recv -F zpool1/b
ackup/d/feher-0
23150:  3458.7027        0.0000 _exit(0)
23089:  3458.7069        0.0000 _exit(0)
22826:  3458.7307        0.0000 _exit(0)
23222:  3458.9040        0.0000 _exit(255)


server: (448 is top level sshd)
    
[[root@thumper1 22:18:44 / 254]]$ egrep '^(2130|2138|1833|1828|2136):' /tmp/truss.out3| egrep 'execve|fork|exit'
1828:   3473.1593        0.0000 fork1()         (returning as child ...)        = 448
1828:   3473.1728        0.0003 fork1()                                         = 1833
1833:   3473.1728        0.0000 fork1()         (returning as child ...)        = 1828
1828:   3473.1782        0.0001 vfork()                                         = 1838
1833:   3473.2895        0.0001 vfork()                                         = 1884
1833:   3473.3462        0.0001 vfork()                                         = 1906
1833:   3473.4028        0.0001 vfork()                                         = 1934
1833:   3473.9794        0.0009 fork1()                                         = 2130
2130:   3473.9794        0.0000 fork1()         (returning as child ...)        = 1833
2130:   3473.9920        0.0016 execve("/bin/bash", 0x08047308, 0x080C73A0)  argc = 3
2130:   3474.0054        0.0002 fork1()                                         = 2136
2136:   3474.0054        0.0000 fork1()         (returning as child ...)        = 2130
2130:   3474.0140        0.0003 fork1()                                         = 2138
2136:   3474.0161        0.0008 execve("/opt/csw/bin/mbuffer", 0x08105F08, 0x08105008)  argc = 9
2138:   3474.0140        0.0000 fork1()         (returning as child ...)        = 2130
2136:   3474.0214        0.0007 execve("/opt/csw/bin/amd64/mbuffer", 0x08047D80, 0x08047DA8)  argc = 9
2138:   3474.0247        0.0008 execve("/usr/sbin/zfs", 0x08105DA8, 0x08105008)  argc = 4
2138:   3476.9014        0.0000 _exit(1)

...
2138:   3476.8998        0.0000 write(2, 0x08096670, 36)                        = 36
2138:      c a n n o t   r e c e i v e   n e w   f i l e s y s t e m   s t
2138:      r e a m
2138:   3476.9000        0.0000 write(2, " :  ", 2)                             = 2
2138:   3476.9001        0.0000 write(2, 0x08096A70, 107)                       = 107
2138:      d e s t i n a t i o n   h a s   s n a p s h o t s   ( e g .   z
2138:      p o o l 1 / b a c k u p / d / f e h e r - 0 @ 2 0 1 5 - 0 4 - 2
2138:      3 - 1 9 4 8 0 0 )\n m u s t   d e s t r o y   t h e m   t o   o
2138:      v e r w r i t e   i t
2138:   3476.9002        0.0000 write(2, "\n", 1)         


so, even  though things start perfectly in synch, this ends up happening, and the mbuffer process is still there even though the zfs recv died. Idon't think this is the only issue, though. It is *an* issue, though.
(If I kill off all the mbuffer and then run in a loop with --runonce it works almost perfectly every time, and on machines with a smaller number of filesystems to snapshot it works well)


Sent from my android device.

-----Original Message-----

**Comment by oetiker** [comment]
so what do you suggest ?

**Comment by DougHughes** [comment]
that is a good question.. this is kind of tricky since it happens on the remote. for the unterminated mbuffer with the exited zfs receive, it is very tricky.. It seems like one option would be for the parent shell to have some sort of timeout. Of course, that has its own pitfalls. A better option might be on the client side. THe client knows whether it has an active, working open mbuffer connection with zfs send already going or not. If it doesn't, it could issue a cleanup ssh to the server side to pkill any mbuffer open and listening on that port.

something more foolproof would be for the parent bash process to keep track of both children and if the zfs exits then kill the mbuffer. That's pretty tricky though. I'm not sure how that would work in practice, myself. 




Sent from my android device.

-----Original Message-----

**Comment by rjeschmi** [comment]
I reported a similar error where mbuffer dies on the receiving end that the sending mbuffer goes to 100% and znapzend doesn't "notice"

https://github.com/oetiker/znapzend/issues/151

I'm going to reach out to the mbuffer author as it seems like something mbuffer should handle on the sending end, but not sure I have all the info.

**Comment by DougHughes** [comment]
Definitely there is a bug in mbuffer to fix. It is ignoring the EPIPE signals from the terminated remote process.

Sent from my android device.

-----Original Message-----

**Comment by rjeschmi** [comment]
Thomas was prompt to respond and I expect he will release a new version of mbuffer soon the error handling problem.

**Comment by DougHughes** [comment]
that's great news, thanks. As soon as it is released I'll see if the 
niksula folks can incoporate it quickly. (don't have contact with the 
csw folks)

**Comment by seshadribpl** [comment]
To add to Doug's (my manager) observations, in many (not all) cases, I have seen mbuffer on the backup server stuck on sleeping (using truss) and have been unable to kill them.

**Comment by rjeschmi** [comment]
the newer version is available here and I've been running it for a while with more stability

http://www.maier-komor.de/mbuffer.html

**Comment by DougHughes** [comment]
great, we'll give it a try. thanks for the update!

Sent from my android device.

-----Original Message-----
