### ISSUE TITLE
Consistent SmartOS KVM snapshots

### ISSUE THREAD

**Issue by aaltonenp** [oetiker/znapzend#171]
On SmartOS, KVM virtual machines have a zone dataset and at least one zfs volume for the guest OS, possibly additional volumes for other guest disks.

The dataset and all the zvols are top level entities under the zones-pool, for example:

```
[root@smartos01 ~]# zfs list
NAME                                               USED  AVAIL  REFER  MOUNTPOINT
zones                                              227G  5.05T   465K  /zones
zones/053e6212-5cbc-4250-ba2c-90a99cae52a3        4.97G  5.03G  4.97G  /zones/053e6212-5cbc-4250-ba2c-90a99cae52a3
zones/053e6212-5cbc-4250-ba2c-90a99cae52a3-disk0  39.1G  5.07T  9.72G  -
zones/053e6212-5cbc-4250-ba2c-90a99cae52a3-disk1  9.77G  5.06T   320K  -
```

For backing up the whole virtual machine in a consistent state, all of these should have their snapshot created at the same point in time, for example:

```
zfs snapshot zones/053e6212-5cbc-4250-ba2c-90a99cae52a3@snap zones/053e6212-5cbc-4250-ba2c-90a99cae52a3-disk0@snap zones/053e6212-5cbc-4250-ba2c-90a99cae52a3-disk1@snap
```

I’m thinking one way to implement this would be to save additional filesystems and/or volumes to snapshot in the configuration for a given master dataset. This way pre- and post-scripts could be per filesystem/volume group and all configuration could be done on the master dataset.

**Comment by kpande** [comment]
you can expose an HTTPS API using SSL certificate authentication to have your storage node commit a snapshot when the VM requests it too, so the data is actually consistent.

**Comment by aaltonenp** [comment]
Yes, that would be a way to do it. For simplicity and a single point of control, I'd like to handle this in the global zone. I could then use a pre-script to send a command to the VM, to checkpoint a database for example. This way all the configuration would in the global zone.

**Comment by psy0rz** [comment]
ZFS-autobackup does this correctly by creating an atomic snapshot per pool.

Please check it out at https://github.com/psy0rz/zfs_autobackup
