### ISSUE TITLE
Question on desired operation

### ISSUE THREAD

**Issue by drajen** [oetiker/znapzend#173]
In a simple example I setup this plan:
`znapzendzetup create SRC '1d=>1min' tank/source1  DST '1d=>1h' root@172.16.202.247:backup/source1_dst `

My expectation is that I will have 1 snapshot taken per minute and maintain those for 1 day. That is true. I expected the destination to be updated once per hour and keep snapshots for a day.

What I observe is that the destination gets it last snapshot updated each minute and have a new snapshot taken each hour.

Ideally, you will only update the destination as requested in the DST plan.

Is this a bug or a feature?

**Comment by martin-rueegg** [comment]
related: https://github.com/oetiker/znapzend/issues/144

**Comment by oetiker** [comment]
it is a missing feature ... patches welcome
