### ISSUE TITLE
minor patches for znapzend 

### ISSUE THREAD

**Issue by DougHughes** [oetiker/znapzend#179]
How would you prefer to receive them?

This one is self explanatory: (see below for delayStagger part of it)

$ diff /opt/csw/lib/ZnapZend/ZFS.pm*
15d14
< has delayStagger    => sub { 0 };
299c298
<         and Mojo::Exception->throw("ERROR: snapshot(s) exist on destination $dstDataSet, but no common "
---
>         and Mojo::Exception->throw('ERROR: snapshot(s) exist on destination, but no common '

Since this one hits us quite a bit, it is very helpful to have the snapshot name in the message.

Another patch that I've been playing around with a --delayStagger option that will add a configurable delay so that if there are lot of things to back up and the resources on the target machine (memory) are limited, that things won't fall over badly. I have some patches I'm working on but am not sure that they are solid yet. (to ZnapZend.pm and the znapzend executable)

PS - the mbuffer patches work really well!

**Comment by oetiker** [comment]
just send pull requests for any fix you have.
