### ISSUE TITLE
Feature request: Disregarding empty snapshots

### ISSUE THREAD

**Issue by ShaRose** [oetiker/znapzend#181]
Hi, I recently had the idea of setting up znapzend where you can 'disregard' empty snapshots where there aren't any changes. I looked at the source a bit, but it doesn't seem like something I'd be able to do myself (I don't know perl, and this is one of those tasks which seems easy as first but likely isn't). Anyways, the idea was to compare the 'new' snapshot with the old one with zfs diff, and if there aren't any differences delete the new snapshot before deleting any older ones.

This could be possible using post-snapshot hooks (set up a script per dataset, find the last 2 snapshots, if the new one is the same as the old one delete it), but I'm not sure how that would affect deleting the older snapshots, and it might be a nice feature to have integrated into znapzend as a boolean in backup plans.

**Comment by oetiker** [comment]
what would be the purpose of this ?

**Comment by ShaRose** [comment]
Well, I like to expose my snapshots over samba with VFS_Shadow_Copy2 and for some of my datasets I want to keep frequent snapshots (game saves, projects, etc), but if I haven't actually made any data I don't want to have to scroll through them finding which one I made the edit in. The easy way to say it is it stops people from using up snapshots when no data actually changed, making the (however many snapshots they are set to keep) only keep snapshots where they might actually want to view instead of checking through a bunch to find which ones actually had any changes at all.

**Comment by oetiker** [comment]
I don't see this as something I would be able to 'sell' to any of our customer ... what they want is to retrieve the state of their home at some particular date ... it is less a matter of when something changed as to what state it was in at some particular point in time ... but by all means, if you want to dig in and find a way how to add this without breaking the system ...
