### ISSUE TITLE
request: new version to get it into OS X homebrew package manager

### ISSUE THREAD

**Issue by JMoVS** [oetiker/znapzend#182]
Homebrew (brew.sh) requires a stable version and as it was only recently that the https://github.com/oetiker/znapzend/commit/7d8427b40e44d64a1d0362aa5f2a361bd95ec2e0 was commited, which drastically simplifies the install. Could you maybe make a 0.14.2 available so then a formula for homebrew could be created easily?

**Comment by martin-rueegg** [comment]
related: https://github.com/oetiker/znapzend/issues/131
(should be working?)

**Comment by oetiker** [comment]
v0.15.2 is out ...
