### ISSUE TITLE
Rotational backup without synchronization

### ISSUE THREAD

**Issue by gusioo** [oetiker/znapzend#186]
Hi!

I want to use rotational snapshots without synchronization to destination. When I create a backup plan with fake destination I get following error:

    Error:
    cannot open 'Undefined/Undefined': dataset does not exist
    *** WARNING: destination 'Undefined/Undefined' does not exist, will be ignored! ***

    cannot open 'Undefined/Undefined': dataset does not exist
    cannot set property for 'Pool-0/dataset': invalid property 'org.znapzend:dst_Undefined_plan'
    could not set property dst_Undefined_plan on Pool-0/dataset

Is there any option to use znapzend in this scenario?

Best regards,
Jacek Fefliński.

**Comment by oetiker** [comment]
I would assume that you could specify a plan where you just don't specify any destination keys ...

**Comment by gusioo** [comment]
Hi!

Thanks for the answer. Works like a charm!

I think we can close this topic.

Best regards,
Jacek Fefliński.
