### ISSUE TITLE
Invent locking when having lot of zfs datasets to snapshot

### ISSUE THREAD

**Issue by fskale** [oetiker/znapzend#192]
Hi Tobi,
we use Smartos 2016 build.
when having a lot zfs datasets to backup, (all workers are started at once and overloading the backup storage), we invented a simple locking mech to overcome this problem.
So, now we have a consecutive sequence and no overloading of the backup storage took place.

We added this to ZFS.pm:

`use Fcntl qw(:flock SEEK_END);`

` sub lock {`
 `my $fh = shift;`
 `flock($fh, LOCK_EX) or return undef;`
 `}`

 `sub unlock {`
 `my $fh = shift;`
 `flock($fh, LOCK_UN) or return undef;`
 `}`

 On function  #spawn event: before spawning receiver process:
 `open(my $snaplock, "<", "/opt/local/var/lock/snapshot.lock")`
                                    `or Mojo::Exception->throw( "Can't open snapshot lockfile: $!" );`

 `lock($snaplock) || Mojo::Exception->throw( "Can't lock snapshot lockfile" );`

At the end of the function:
 `unlock($snaplock) || Mojo::Exception->throw( "Can't unlock snapshot lockfile" );`

Perhaps you will think about adding some locking mech.

Rgds.
Franz

**Comment by hadfl** [comment]
if i got you right, your problem is not the snapshotting but the send/recv workers.

have a look at the `post_snap_cmd` option. you could trigger a script which does locking there. no need to patch znapzend...

**Comment by fskale** [comment]
Hi, that we did before.
The problem is, that the spawning of the receiverprocesses starts in parallel.
When having a lot of receiver processes, they will all consume a lot of memory. Sure, we can size down mbuffer, what we actually did. Nevertheless it was too much for our backup storage because we have a huge amount of parallel backups. So we  tried our locking solutions which works perfect.

Rgds.
Franz

**Comment by hadfl** [comment]
well, yeah...  obviously `post_snap_cmd` won't work w/ your flock approach but you could create a script that counts "zfs send" processes and terminates if the number is less than x... w/ this approach you could define how many send/receives run in parallel...

**Comment by fskale** [comment]
Hi,
we had this already, but terminating a running process or changing a script every time i add backups was now the way to go for us. Consider a very large environment. So adding 5 lines was sufficient for our large environment. There's no problem to add the option for large enviroments i think. And it's only a hint. Every large installation will run into the same problem. And you don't want to have parallel snapshots on large installations. And i worked on really large installations, so you have to meticulously fine tune your snapshot policies. On small installations, sure you will want to do parallel snapshots.
Perhaps anyone with a big bunch of zfs datasets can think of this as a way to go.
Btw. Tobias great software anyhow.

Rgds.
Franz

**Comment by hadfl** [comment]
you got me wrong. have a look at the pseudocode below. that would be your post_snap_cmd script. you don't have to terminate any running process and you don't have to adjust the script every time you add backups. i was talking about the post_snap_cmd script that will terminate once the send process count will be less than x, i.e. another send process will start.
```
while(1) {
    exit if send_proc_count < x;
    sleep 1;
}
```
actually, the initial request we got to implement parallel send/recv was for a 5PB storage with several hundreds of datasets (so not so small i think). fine tuning of send/recv staggering was done via post_snap_cmd

**Comment by fskale** [comment]
Hi,
It's not about the amount of space, it's about the memory. If the receive worker starts, it will allocate the memory as defined. Consider 200 Snapshots at parallel with a 16MB buffer size. About 3,2T RAM.   ;-) Exiting a snapshot run is not an option. So we decided to use queuing by flock. And we tried to cover it with the post script which was not they way to go.

**Comment by oetiker** [comment]
@fskale what @hadfl is trying to tell you, is that you could could write a little script that blocks until the number of active zfs send processes falls under a certain number and then continues.

**Comment by oetiker** [comment]
AND if you are running any sizeable zfs depoyment on a system where you can not spare 3.2 GB ram then ... our zfs boxes have 128 GB Ram as a starting point ... most actually have 256 GB and if I bought a new one today it would probaly get 512 GB

**Comment by fskale** [comment]
Hi Tobias,
i think you talked some time ago to my colleague about the issue, and what we've done already. We downsized the default setting to 16MB. Your solution we tried already with the same outcome. It was only a info that we covered the problem by using locking.

Rgds.

Franz

**Comment by oetiker** [comment]
ok

**Comment by aarononeal** [comment]
I hit this same issue with a large number of datasets and a slow network. You might consider bundling a `znapwait` script if you don't want to make parallelism a configurable option.

I solved this for now with:

```
#!/bin/csh
while ( `ps -A -o command | grep '^sh -c zfs send' | wc -l` > 0 )
  sleep `jot -r 1 1 10`
end
```

**Comment by aarononeal** [comment]
By the way, this solution isn't ideal for every configuration because waiting post snaps will delay taking additional snapshots if a large send backs up the queue by running longer than other datasets' snap plan windows. Ideally snap and send would be decoupled, and that does not appear possible with a `post_snap_cmd` solution.
