### ISSUE TITLE
First synchronization cycle does not create dataset on the remote location

### ISSUE THREAD

**Issue by raveenpl** [oetiker/znapzend#195]
Hi,

In these two following cases znapzend work in a different way:

1. Create znapzend task when there's no destination dataset created. Synchronization will not work until remote dataset is created. 

`[Tue Mar 15 15:35:49 2016] [warn] destination 'root@192.168.251.130:Pool-0/test' does not exist or is offline. will be rechecked every run...`

2. Create znapzend task when there's destination dataset created. Synchronization works. Delete destination dataset. Dataset will be created automatically at the next round.

```
root@192.168.251.130:~$ zpool history 
History for 'Pool-0':
...
2016-03-16.10:29:31 zfs destroy Pool-0/test -r -R -f

root@192.168.251.130:~$ zfs get version Pool-0/test
cannot open 'Pool-0/test': dataset does not exist
```

```
root@192.168.251.130:~$ zpool history 
History for 'Pool-0':
...
2016-03-16.10:29:31 zfs destroy Pool-0/test -r -R -f
2016-03-16.10:30:17 zfs recv -F Pool-0/test

root@192.168.251.130:~$ zfs get version Pool-0/test
NAME         PROPERTY  VALUE    SOURCE
Pool-0/test  version   -        -
```

What do you think about unifiynig this behaviour? In both cases destination dataset could be created automatically when it does not exist on the destination location. As an addition there could be added "check" if destination location has sufficient size for dataset to be created.

Regards,
PK

**Comment by oetiker** [comment]
I just merged a PR which adds an option to create any remote fileset ...
