### ISSUE TITLE
Schedule removed datasets

### ISSUE THREAD

**Issue by Wouter0100** [oetiker/znapzend#197]
Some awesome features that would make ZnapZend rock:
- When a dataset is removed on SRC, it should still cleanup the snapshots on the DST according to the schedule.
- When a dataset on DST is empty (after cleaning all snapshots), it could be removed from DST.

**Comment by oetiker** [comment]
there is a fundamental design problem with this ... since the configuration resides in the properties of the SRC dataset. When the SRC dataset is gone, znapzend does not know it ever existed.

**Comment by Wouter0100** [comment]
Hmm, aren't those properties copied to the DST? If not, I more meant the recursive datasets (which doesn't store any info, only the "parent").

**Comment by oetiker** [comment]
properties don't get copied ... afaik ... but in recursive sources this should be possible, yes ... got a patch ?

**Comment by Wouter0100** [comment]
Nope, not yet. I'll open a PR when I have created. I currently don't have enough time to implement this with my level of experience with Perl.
