### ISSUE TITLE
can't open /usr/local/bin/lock_flush_db.sh

### ISSUE THREAD

**Issue by qwerty3656** [oetiker/znapzend#198]
The only files in /usr/local/bin are: znapzend znapzendzetup and znapzendztatz.  I've run the setup several times but it does not appear the other files are being created.  Note: The setup also did not automatically install mbuffer (I apt-get'd it)

**Comment by oetiker** [comment]
`lock_flush_db.sh` is a mockup file name from the documentation ... apt-getting mbuffer is outside the scope of a proper configure make install run ... but what configure could do would be to check for the presence of mbuffer and warn if it does not find it.
