### ISSUE TITLE
Remote DST ssh port

### ISSUE THREAD

**Issue by mattronix** [oetiker/znapzend#201]
Hi Oetiker,

How can i specify the SSH port for a remote server? 

Thanks!! :)

**Comment by moetiker** [comment]
----- Original Message -----
> From: "Matthew Frost" <notifications@github.com>
> To: "oetiker/znapzend" <znapzend@noreply.github.com>
> Sent: Friday, April 1, 2016 4:24:40 PM
> Subject: [oetiker/znapzend] Remote DST ssh port (#201)

> Hi Oetiker,
> 
> How can i specify the SSH port for a remote server?
> 
> Thanks!! :)

Hi

You can configure this in the ~/.ssh/config of the running user.

cheers Manuel

--
Manuel Oetiker, OETIKER+PARTNER AG, Aarweg 15 CH-4600 Olten
http://www.oetiker.ch manuel@oetiker.ch +41 62 775 9901

**Comment by mattronix** [comment]
Thanks vaild point did not think of that :P (silly me)

Thanks! :)
