### ISSUE TITLE
Issue on hourly snapshots

### ISSUE THREAD

**Issue by tisc0** [oetiker/znapzend#208]
The hourly snapshots stopped working locally (and remotely, then), and worked back, when I changed the plan of a dataset.

Non-working plan :
dst_stor1_plan  = 3days=>1hour,2days=>4hours,30days=>1day
src_plan        = 2days=>1hour,2days=>4hours,3days=>1day

Working plan :
dst_stor1_plan=2days=>1hours,3days=>4hours,30days=>1days
src_plan=1days=>1hours,2days=>4hours,4days=>1days

No error message in logs (journalctl)
- Might not like same number of days for 1h&4h retention on src_plan
- Might not like inferior number on 4h snaps compared to hourly ones

Thanks

Issue encountered with znapzend version 0.15.3 & 0.15.4
OS : CentOS Linux release 7.1.1503 (Core) 
zol version : zfs-0.6.5.6-1.el7.centos.x86_64

**Comment by hadfl** [comment]
> src_plan = 2days=>1hour,2days=>4hours,3days=>1day

same issue as here: https://github.com/oetiker/znapzend/issues/231#issuecomment-246381899
has been fixed: https://github.com/oetiker/znapzend/pull/232
