### ISSUE TITLE
Scheduling znapzend

### ISSUE THREAD

**Issue by alaricljs** [oetiker/znapzend#212]
I have a need to schedule when snapshotting occurs so that the process doesn't interupt usage of the VM being snapshotted.  As an example, I'd like it to snapshot daily but only between 1am and 2am.

Is this presently possible with cron and --runonce?  Is this a possible feature?

**Comment by oetiker** [comment]
You could configure a `pre-snap-command` of `sleep 7200`and snapshot daily. Running by cron might work, but I have not tested it.
