### ISSUE TITLE
System V Init Script

### ISSUE THREAD

**Issue by Ryushin** [oetiker/znapzend#214]
Please provide a System V Init script for those that do not run systemd.

**Comment by oetiker** [comment]
if you submit a PR, I will be glad to merge it ... we use znapzend  on omnios and hence do not need system v init

**Comment by Ryushin** [comment]
I've been using this init script for better part of a year on Devuan with no issues:

[znapzend.syvinit.txt](https://github.com/oetiker/znapzend/files/2741794/znapzend.syvinit.txt)
