### ISSUE TITLE
The checkinstall script adds dependency on zfsutils package, but Ubuntu 16.04 has package zfsutils-linux

### ISSUE THREAD

**Issue by lckarssen** [oetiker/znapzend#220]
The `checkinstall.sh` script mentions package `zfsutils` as a dependency. However, for Ubuntu 16.04 the package is called `zfsutils-linux`. 

For a correct fix the dependency should check which Ubuntu version it is running on, since older distro's (e.g. 14.04 LTS) will have the package with the old name.

**Comment by albundy83** [comment]
A question about this commit, if you plan to use zfsonlinux instead of the distribution packages, this commit prevent it from running.

**Comment by oetiker** [comment]
Patches welcome!

**Comment by albundy83** [comment]
What about this way ?
https://github.com/oetiker/znapzend/pull/318
