### ISSUE TITLE
Alerting / Notifications (via email or other mechanism)

### ISSUE THREAD

**Issue by michaeljsmalley** [oetiker/znapzend#223]
It would be nice if email notifications were a part of znapzend for various success / failure states. Setting an email address for each given backup schedule might be one elegant way to handle this (so that different pools can notify different people who use those pools if there is an issue with znapzend replication).

**Comment by knoblochtobias** [comment]
Hi, I just found this workaround:
You can use this python script in combination with Nagios, healthchecks.io or a similar service:
https://github.com/asciiphil/check_znapzend
