### ISSUE TITLE
znapzend recursive with exact replication

### ISSUE THREAD

**Issue by gbulfon** [oetiker/znapzend#234]
Hi, I just started using znapzend, and after configuring a recusrive plan on a large pool, I found replication was not keeping all my original zfs options: for example, original dataset compression is not kept on destination.
Also I had to use --autoCreation, or I would receive errors.
I bet autoCreation is not creating the destination dataset exactly as the original.

How can I achieve an exact replica with znapzend? I used to have it exactly replicated with zfs send/recv.

Thanks,
Gabriele

**Comment by oetiker** [comment]
not all properties get passed on through send receive ... that is true and intentional ... unfortunately the illumos zfs recv does not allow property filtering like the solaris one ... 

znapzend does use pure zfs send recv and and does not mess with the properties afterwards ... 

note that properties get overwritten on receive, so setting properties on create has no effect AFAIK

feel free to propose patches if you see anything that can be improved !

**Comment by gbulfon** [comment]
This is true when doing send/recv of single datasets.
When using a "zfs send -Rv ... data@snapname | zfs recv -Fd data-backup", the pool is fully replicated, including properties, as a complete substitute of the original.

I think something like this is necessary if znapzend is used to have an exact copy.

**Comment by octo777** [comment]
I was hoping to use it to make an exact copy of datasets on a remote server. So this will be a problem still?

**Comment by oetiker** [comment]
you do get an exact copy except that the shares will not be mounted by default ... best is to test to see if is what you need.

**Comment by gbulfon** [comment]
and except not all zfs properties are preserved

**Comment by oetiker** [comment]
which one are you missing ?

**Comment by gbulfon** [comment]
I will have to check again, but as I stated at the beginning of the thread : "for example, original dataset compression is not kept on destination". Cannot say what's going to happen to zone datasets properties.

**Comment by oetiker** [comment]
note that only properties that are locally defined will be sent in any event not properties received or inherited afaik

**Comment by gbulfon** [comment]
Hi, I got back to znapzend recently and still facing this problem: properties are not replicated.
Important properties include: compression, zoned, mountpoint.
While a zfs send -R will replicate any descendant and their properties, znapzend design run send for each source dataset creating the destination dataset the first time with default properties, while it would be nice if an option would force the code to look at the source for a minimum set of properties (compression, zoned, mountpoint, but maybe others?) to be set identical on destination creation.
The problem with -R is that it will not permit to keep more snapshots on destination than what I have at source, becuase replica will force destination to have identical snaphots.
Znapzend solve this by treating each dataset one by one.
I think a replica mode that considers properties during dataset creation on destination would be a great option.
