### ISSUE TITLE
Can't exec "zfs": No such file or directory

### ISSUE THREAD

**Issue by xorinzor** [oetiker/znapzend#236]
When I try to run `znapzend --noaction --debug` after following the steps as described in the README.MD; I get the message:

`Can't exec "zfs": No such file or directory at /opt/znapzend-0.15.7/lib/ZnapZend/ZFS.pm line 133.`

How can I fix this?
Running CentOS 6

**Comment by Gregy** [comment]
What happens when you enter just ```zfs``` into the same terminal?

**Comment by xorinzor** [comment]
`-bash: zfs: command not found`

Which isn't really suprising me, but I don't know what to install either .

The only package that I can find is `zfs-fuse.x86_64 : ZFS ported to Linux FUSE` although I have no idea if this is the correct one.

I think it's worth adding installation instructions for all dependencies in the README nonetheless

**Comment by Gregy** [comment]
Well znapzend is only useful if you already have working zfs that you wish to backup. If you do not use zfs it can do nothing for you.

**Comment by vasile-gh** [comment]
@xorinzor did you try `sudo zfs`? Not @home but I seem to remember that this is what you get unless you run it as root.

**Comment by xorinzor** [comment]
@vasile-gh I was running it as root

**Comment by vasile-gh** [comment]
Not sure about CentOS but in Debian zfs is compiled from source through
dkms
