### ISSUE TITLE
znapzend does not wait until transfer finishes before beginning a new one

### ISSUE THREAD

**Issue by Gregy** [oetiker/znapzend#237]
If I set short backup interval (15 minutes for example) znapzend does not finish the first transfer (it can be large) in time before next scheduled transfer.

At this point I would expect znapzend to emit warning message, set up the snapshot but wait until the first transfer finishes before starting a second transfer for the same dataset.

What do you think?

**Comment by oetiker** [comment]
yes ... this is what it does ... does it not work like that for you ?

**Comment by Gregy** [comment]
Well, I dug into it and you are of course right. I would have sworn I saw two zfs sends with the same dataset running at once but I cannot replicate it. It may have been a brain fart.

Thank you
