### ISSUE TITLE
Cleanup of aged out snapshots fails

### ISSUE THREAD

**Issue by se-mh** [oetiker/znapzend#241]
I just compiled and installed znapzend on a Solaris 10 x86-64 host running Solaris 10 1/13 including the latest recommended patchset.

I created a simple relationship for testin znapzend. Therefore I have a dataset name "data_sata/media" and I do snapshots every minute, which works fine.

After a couple of minutes minutes I altered the relation to keep them for 5 minutes only to test if also the cleanup works. The cleanup fails with the following error:

> [Tue Nov  8 12:06:06 2016] [info] znapzend (PID=21306) starting up ...
> [Tue Nov  8 12:06:06 2016] [info] refreshing backup plans...
> [Tue Nov  8 12:06:06 2016] [info] found a valid backup plan for data_sata/media...
> [Tue Nov  8 12:06:06 2016] [info] znapzend (PID=21306) initialized -- resuming normal operations.
> [Tue Nov  8 12:06:06 2016] [debug] snapshot worker for data_sata/media spawned (21534)
> [Tue Nov  8 12:06:06 2016] [info] creating snapshot on data_sata/media
> zfs snapshot data_sata/media@2016-11-08-120606
> [Tue Nov  8 12:06:06 2016] [debug] snapshot worker for data_sata/media done (21534)
> [Tue Nov  8 12:06:06 2016] [debug] send/receive worker for data_sata/media spawned (21537)
> [Tue Nov  8 12:06:06 2016] [info] starting work on backupSet data_sata/media
> zfs list -H -o name -t snapshot -s creation -d 1 data_sata/media
> [Tue Nov  8 12:06:06 2016] [debug] cleaning up snapshots on data_sata/media
> zfs destroy data_sata/media@2016-11-08-114500,2016-11-08-114600,2016-11-08-114700,2016-11-08-114800,2016-11-08-114900,2016-11-08-115000,2016-11-08-115100,2016-11-08-115200,2016-11-08-115300,2016-11-08-115400,2016-11-08-115500,2016-11-08-115600,2016-11-08-115700,2016-11-08-115800,2016-11-08-115900,2016-11-08-120000,2016-11-08-120100
> **cannot open 'data_sata/media@2016-11-08-114500,2016-11-08-114600,2016-11-08-114700,2016-11-08-114800,2016-11-08-114900,2016-11-08-115000,2016-11-08-115100,2016-11-08-115200,2016-11-08-115300,2016-11-08-115400,2016-11-08-115500,2016-11-08-115600,2016-11-08-115700,2016-11-08-115800,2016-11-08-115900,2016-11-08-120000,2016-11-08-120100': invalid dataset name**
> [Tue Nov  8 12:06:07 2016] [warn] ERROR: cannot destroy snapshot(s) data_sata/media@2016-11-08-114500
> [Tue Nov  8 12:06:07 2016] [info] done with backupset data_sata/media in 1 seconds
> [Tue Nov  8 12:06:07 2016] [debug] send/receive worker for data_sata/media done (21537)

It seems like the collected datasets are merged into a single zfs destroy command, which Solaris ZFS does not understand. Is this a Solaris-only problem? Do you have a workaroud for this?

**Comment by oetiker** [comment]
you may want to start znapzend with `--features=oracleMode`
