### ISSUE TITLE
Using without creating snapshots

### ISSUE THREAD

**Issue by lnxbil** [oetiker/znapzend#248]
Hi all,

I'm filling my ZFS pool with backups from an external source and snapshotting after updating files on the filesystems with the timestamp according to the backup filename. Therefore, I do not need the automatic snapshot creating feature, in fact, I do not want it. Is there any way to deactivate that? I just want to use ```zsnapzend``` for send/receive automation and automatic thinning. Is there a way I'm not aware of to achieve the wanted setup?

Best,
Andreas

**Comment by oetiker** [comment]
this is not a feature presently supported by znapzend
