### ISSUE TITLE
Where are configurations stored and loaded from?

### ISSUE THREAD

**Issue by 0xABAB** [oetiker/znapzend#258]
```
Do you want to save this backup set [y/N]? y
NOTE: if you have modified your configuration, send a HUP signal
```
It is not documented where or how this is saved.

**Comment by oetiker** [comment]
https://github.com/oetiker/znapzend/blob/master/doc/znapzend.pod

> ZnapZend reads its configuration from custom properties in the fileset. Use znapzendzetup to set these properties.
