### ISSUE TITLE
Document 'plan' in a POSIX fashion

### ISSUE THREAD

**Issue by 0xABAB** [oetiker/znapzend#259]
The synopsis being used within this program's documentation is non-standard (i.e. not POSIX compatible). The most awful offender would be the 'plan' argument. That should be <plan>, not 'plan'. 

In fact, you are using SRC and plan on the same line where SRC is supposed to be a terminal symbol and plan is a non-terminal.

**Comment by oetiker** [comment]
please feel free to help improving the structure of the documentation by providing a PR
