### ISSUE TITLE
Error messages are terrible

### ISSUE THREAD

**Issue by 0xABAB** [oetiker/znapzend#260]
Running as root:
```
# ./znapzend --noaction
Permission denied the ZFS utilities must be run as root.
```
Seriously?

Perhaps this is the *remote* side outputting this, but it's *your* program which displays it to me. 

If so, you should output: "Please configure the remote system in such a way that zfs list can be run as user foobar". 

I am wondering what brought you to open-sourcing this socalled "program". It is not documented in any sane fashion, the technical choices you made are rather terrible, the program is written as if it comes straight out of the nineties, it is written in Perl, when backups are actually important enough to be written in a language with static types, etc. All in all it seems your program is just one big clusterfuck (a technical term).  So, please, enlighten us. Why did you decide to share this "marble" with the rest of humanity?

**Comment by oetiker** [comment]
Sorry for offending you with this package ... we will try todo to better in the future. Thanks for your valuable suggestions.
