### ISSUE TITLE
Error parsing time

### ISSUE THREAD

**Issue by christophwicki** [oetiker/znapzend#263]
Since some time, I get the following error (preventing from cleanup old snaps):

emerald[znapzend-0.17.0/bin]# ./znapzend --noaction --runonce=rpool/ROOT/omnios
[Thu Feb  9 14:20:05 2017] [info] znapzend (PID=5683) starting up ...
[Thu Feb  9 14:20:05 2017] [info] refreshing backup plans...
[Thu Feb  9 14:20:05 2017] [info] found a valid backup plan for rpool/ROOT/omnios...
[Thu Feb  9 14:20:05 2017] [info] znapzend (PID=5683) initialized -- resuming normal operations.
[Thu Feb  9 14:20:05 2017] [debug] snapshot worker for rpool/ROOT/omnios spawned (5688)
[Thu Feb  9 14:20:05 2017] [info] creating recursive snapshot on rpool/ROOT/omnios
[Thu Feb  9 14:20:05 2017] [debug] snapshot worker for rpool/ROOT/omnios done (5688)
[Thu Feb  9 14:20:05 2017] [debug] send/receive worker for rpool/ROOT/omnios spawned (5689)
[Thu Feb  9 14:20:05 2017] [info] starting work on backupSet rpool/ROOT/omnios
[Thu Feb  9 14:20:05 2017] [debug] sending snapshots from rpool/ROOT/omnios to big/zz/root/omnios
[Thu Feb  9 14:20:10 2017] [warn] send/receive for rpool/ROOT/omnios failed: Error parsing time at /usr/perl5/5.16.1/lib/i86pc-solaris-thread-multi-64int/Time/Piece.pm line 469.

Is this a know problem?
Regards,
Christoph

**Comment by oetiker** [comment]
Not to my knowledge ... if you could patch your Piece.pm so that it tells which arguments it does not like, that might help to get to the bottom of this

**Comment by christophwicki** [comment]
With a debugging statement, I found a snapshot on the dst_a pool with a wrong (but quite similar) date format:
big/zz/root/omnios@2016-08-12-14:59:49
and the normal snaps look like: 2016-08-12-14.59.45

thanks for the hint!

**Comment by hadfl** [comment]
timeformat gets transformed to a "snapshot filter":
https://github.com/oetiker/znapzend/blob/master/lib/ZnapZend/Time.pm#L239

the dot character should be escaped since it matches everything.
