### ISSUE TITLE
Debian Jessie dependency problem

### ISSUE THREAD

**Issue by josci** [oetiker/znapzend#265]
Hi,

I'm using znapzend for quite while now. Absolute fantastic tool!!

I upgraded my NAS from Debian Wheezy to Jessie. Therefor I have to reinstall znapzend. The make command throws the following error (I think it is a missing dependency)

> /tmp/znapzend-0.17.0# make
Making all in thirdparty
make[1]: Entering directory '/tmp/znapzend-0.17.0/thirdparty'
  GEN      touch
! Couldn't find module or a distribution CPAN::Meta (2.142060)
! Installing the dependencies failed: Installed version (2.140640) of CPAN::Meta is not in range '2.142060'
! Bailing out the installation for Module-Build-0.4218.

**Comment by oetiker** [comment]
try

```
touch PERL_MODULES
make
```

**Comment by josci** [comment]
problem fixed. Thanks!
