### ISSUE TITLE
Test failed: t/znapzend.t     (Wstat: 0 Tests: 6 Failed: 1)

### ISSUE THREAD

**Issue by cgrzemba** [oetiker/znapzend#266]
How can I investigate, what is going wrong here?

Test Summary Report
-------------------
t/znapzend.t     (Wstat: 0 Tests: 6 Failed: 1)
  Failed test:  5
  Parse errors: Plan (1..5) must be at the beginning or end of the TAP output
                Tests out of sequence.  Found (5) but expected (6)
                More than one plan found in TAP output
                Bad plan.  You planned 5 tests but ran 6.

**Comment by cgrzemba** [comment]
try to build version 0.17.0

**Comment by oetiker** [comment]
hmmm there are only 5 tests ...  how are you trying to run the tests?

**Comment by cgrzemba** [comment]
$ gmake check
on Solaris 11.2.6.4.0 Sparc on OpenCSW buildfarm
