### ISSUE TITLE
Show what snapshots are to be removed

### ISSUE THREAD

**Issue by Freeaqingme** [oetiker/znapzend#269]
I'm building a little gui for my users so they can select a snapshot they wish to restore their data from. As such, I retrieve a list of snapshots using 'zfs list -t snapshot'. However, if a user would be presented such a list right before znapzend does a clean-up round, chances are that the snapshot would be deleted before the user had a chance to restore it.

Therefore, I'd like to only show the snapshots that won't be removed within the next X (say 15) minutes. However, to accomplish that it would be awesome if znapzend would have a feature that returned the expiration date (assuming the retention scheme doesn't change) of all snapshots. Or, alternatively, allow to do a dry-run with some future date so one could see what znapzend would do at that time.

Thanks for this awesome tool :)

**Comment by oetiker** [comment]
PRs for new features are certainly welcome! and if you have a budget, please let us know so we can make an offer.

**Comment by Freeaqingme** [comment]
@oetiker I'm certainly willing to give it a try. Any pointers on what approach you'd deem most viable?

**Comment by hadfl** [comment]
you should have a look at the `Time.pm` module. All relevant methods should be there. Especially: https://github.com/oetiker/znapzend/blob/master/lib/ZnapZend/Time.pm#L149

**Comment by Freeaqingme** [comment]
@oetiker I sent you an email ten days ago to the address listed on your Github profile. Did you receive that, by any chance?

**Comment by oetiker** [comment]
Hi dolf, yes ... see your mail ...

**Comment by Freeaqingme** [comment]
This was implemented in 172d4759fe43101ae71f260565c69597d006c98a , thanks!

=> Closed.
