### ISSUE TITLE
znapzend fails on Ubuntu Server 17.04 

### ISSUE THREAD

**Issue by naegling** [oetiker/znapzend#271]
znapzend and both support utilities report:

ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xdb80080)

To the best of my knowledge, this worked on 16.10. Removed original install and git repo, re-cloned and reinstalled with same results.

**Comment by cro** [comment]
That's funny, I had the same problem and applied your solution, but it worked for me. I don't remember my exact procedure though. I might have nuked the install dir, done `make clean` and then `make install`.

**Comment by naegling** [comment]
disregard. I tried trying again. must have fat-fingered the process somewhere ;-O
