### ISSUE TITLE
znapzend fails with "cannot open 'mypool/backups/foo/bar': dataset does not exist" error

### ISSUE THREAD

**Issue by minorsatellite** [oetiker/znapzend#274]
Attempting to kick off a manual, initial sync but it fails. The data set on the receiving side without a doubt exists.

```
znapzend -d -n --autoCreation --noaction --runonce=qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
[Wed May 31 00:15:39 2017] [info] znapzend (PID=16086) starting up ...
[Wed May 31 00:15:39 2017] [info] refreshing backup plans...
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:40 2017] [info] running pre-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:40 2017] [warn] command 'zfs unmount -f mypool/backups/foo/bar' failed
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs list -H -o name -t 'filesystem,volume' mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs list -H -o name -t 'filesystem,volume' zpool1
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs create -p mypool/backups/foo/bar
[Wed May 31 00:15:41 2017] [info] creating destination dataset 'root@10.100.10.21:mypool/backups/foo/bar'...
[Wed May 31 00:15:41 2017] [info] found a valid backup plan for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar...
[Wed May 31 00:15:41 2017] [info] running post-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:41 2017] [warn] command 'zfs mount mypool/backups/foo/bar' failed
[Wed May 31 00:15:41 2017] [info] znapzend (PID=16086) initialized -- resuming normal operations.
[Wed May 31 00:15:41 2017] [debug] snapshot worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar spawned (16143)
[Wed May 31 00:15:41 2017] [info] creating recursive snapshot on qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
# zfs snapshot -r qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar@2017-05-31-001541
[Wed May 31 00:15:41 2017] [debug] snapshot worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar done (16143)
[Wed May 31 00:15:41 2017] [debug] send/receive worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar spawned (16144)
[Wed May 31 00:15:41 2017] [info] starting work on backupSet qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
# zfs list -H -r -o name -t filesystem,volume qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
[Wed May 31 00:15:41 2017] [info] running pre-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:41 2017] [warn] command 'zfs unmount -f mypool/backups/foo/bar' failed
[Wed May 31 00:15:41 2017] [debug] sending snapshots from qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar to root@10.100.10.21:mypool/backups/foo/bar
# zfs list -H -o name -t snapshot -s creation -d 1 qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs list -H -o name -t snapshot -s creation -d 1 mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs list -H -o name -t snapshot -s creation -d 1 mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:43 2017] [debug] cleaning up snapshots on root@10.100.10.21:mypool/backups/foo/bar
[Wed May 31 00:15:43 2017] [info] running post-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 00:15:43 2017] [warn] command 'zfs mount mypool/backups/foo/bar' failed
# zfs list -H -o name -t snapshot -s creation -d 1 qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
[Wed May 31 00:15:43 2017] [debug] cleaning up snapshots on qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar
[Wed May 31 00:15:43 2017] [info] done with backupset qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar in 2 seconds
[Wed May 31 00:15:43 2017] [debug] send/receive worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/foobar done (16144)
```

**Comment by oetiker** [comment]
when you manually login, the commands succeed ?

**Comment by minorsatellite** [comment]
If you mean manually login on the source host no it does not. I am running the command as root user manually from the source host.

**Comment by oetiker** [comment]
znapzend is not magic in that way ... something does not work on the command line, znapzend can not make it work ...

**Comment by minorsatellite** [comment]
I have manual snapshots and send/receive working on a different dataset, so broken zpool/datasets can be eliminated. 

Znapsend is complaining about a missing dataset that does actually exist, so no magic required.

If you have a better test regimen in mind, I am listening.

Thx.

**Comment by oetiker** [comment]
aehm ... looking at your codeagain ... you are running in noaction mode ... what would you  like to happen ?

**Comment by minorsatellite** [comment]
As a dry run I would like to see that it would complete successfully without errors, as the noaction flag suggests.

Am I not understanding that flag correctly?

**Comment by oetiker** [comment]
The `--noaction` flag causes all actions that cause permanent alterations to the system to NOT happen ... depending on the state your system is in, this will have different effects as you can observe.

see https://github.com/oetiker/znapzend/tree/master/t to learn how we approach testing in this scenario.

**Comment by minorsatellite** [comment]
Removing the “—noaction" flag did not resolve the issue. Can you reopen?

**Comment by minorsatellite** [comment]
Datasets on remote host:

admin@myhost:~$ sudo zfs list -t filesystem
[sudo] password for admin:
NAME                    USED  AVAIL  REFER  MOUNTPOINT
mypool                 23.0T  53.7T   279K  /mypool
mypool/backups          558K  53.7T   279K  /mypool/backups
mypool/backups/foo   279K  53.7T   279K  /mypool/backups/foo

**Comment by minorsatellite** [comment]
I resolved the issue by deleting and recreating the replication plan and issuing the HUP command. Its likely that my initial faulty install was to blame, however its still compelling about a missing dataset eventhoug the dataset exists and the backup is running (see below).

Lastly, I am getting very poor performance at 5Mb/sec over a high speed connection, using the default mbuffer parameters. Any suggestions on optimal settings. Data is replication in same metro area over 100Mb connection on send side, and 1Gb on receive side.

root@myhost:~# znapzend -d --autoCreation --runonce=qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar
[Wed May 31 11:03:40 2017] [info] znapzend (PID=2012) starting up ...
[Wed May 31 11:03:40 2017] [info] refreshing backup plans...
[Wed May 31 11:03:41 2017] [info] running pre-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 11:03:41 2017] [warn] command 'zfs unmount -f mypool/backups/foo/bar' failed
[Wed May 31 11:03:41 2017] [info] found a valid backup plan for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar...
[Wed May 31 11:03:41 2017] [info] running post-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 11:03:41 2017] [warn] command 'zfs mount mypool/backups/foo/bar' failed
[Wed May 31 11:03:41 2017] [info] znapzend (PID=2012) initialized -- resuming normal operations.
[Wed May 31 11:03:41 2017] [debug] snapshot worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar spawned (2036)
[Wed May 31 11:03:41 2017] [info] creating recursive snapshot on qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar
# zfs snapshot -r qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar@2017-05-31-110341
[Wed May 31 11:03:41 2017] [debug] snapshot worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar done (2036)
[Wed May 31 11:03:41 2017] [debug] send/receive worker for qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar spawned (2038)
[Wed May 31 11:03:41 2017] [info] starting work on backupSet qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar
# zfs list -H -r -o name -t filesystem,volume qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar
[Wed May 31 11:03:41 2017] [info] running pre-send-command for root@10.100.10.21:mypool/backups/foo/bar
cannot open 'mypool/backups/foo/bar': dataset does not exist
[Wed May 31 11:03:41 2017] [warn] command 'zfs unmount -f mypool/backups/foo/bar' failed
[Wed May 31 11:03:41 2017] [debug] sending snapshots from qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar to root@10.100.10.21:mypool/backups/foo/bar
# zfs list -H -o name -t snapshot -s creation -d 1 qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar
# ssh -o batchMode=yes -o ConnectTimeout=30 root@10.100.10.21 zfs list -H -o name -t snapshot -s creation -d 1 mypool/backups/foo/bar
# zfs send qs-9ebd0a2d-883d-0519-84db-145402c0eef0/bar@2017-05-31-110341|ssh -o batchMode=yes -o ConnectTimeout=30 'root@10.100.10.21' '/usr/bin/mbuffer -q -s 128k -W 60 -m 1G|zfs recv -F mypool/backups/foo/bar'
