### ISSUE TITLE
Improving znapzend/mbuffer performance

### ISSUE THREAD

**Issue by minorsatellite** [oetiker/znapzend#275]
Question 1:
This is not so much an issue as it is an inquiry. I have been underwhelmed with the observed performance of mbuffer in conjunction with ZFS send/receive. Even over a relatively fast, low latency link, I have never been able to climb above 11Mb/sec on the receive side (based on what I am observing via iostat). I have modified the mbuffer size/setting on the send side from 1G to 50M, something more commensurate with the know link speed, but I have not seen any improvement.

Question 2:
I have a relatively updated copy of the dataset on the remote host (receive side) on the same pool that I am trying to replicate using znapzend. Its a synced dataset that I have been manually maintaining until I could znapzend fully operational. I created it by pre-seeding data from the send size using an ZFS send output file. 

My question is, can I pre-seed the znapzend replicated data in a similar fashion given that znapzend has its own snapshot mechanism? Ideally I would like to send/receive from that dataset on the same Zpool to the znapzend managed dataset...

**Comment by oetiker** [comment]
dear minor satellite, this is NOT your private hotline for znapzend but the znapzend bugtracker ... for support (as mentioned on your website, please use the gitter chat and stack exchange)

* ssh performance depends on ssh encryption settings to a large extent ... use the .ssh/config to tune this. you can also configure znapzend to bypass ssh and send from mbuffer to mbuffer forgoing encryption ... 
* you can certainly pre-seed just put the snapshot in the right place and giving it the same name on the sending and receiving end ...

**Comment by minorsatellite** [comment]
Thanks for the clarification, and thanks for making me aware of Gitter Chat.
