### ISSUE TITLE
Cant create plan with two equal retention times

### ISSUE THREAD

**Issue by simt2** [oetiker/znapzend#276]
Im still new to znapzend, but from my understanding the plan `1day=>1day,1day=>1month'` should give me snapshots every day and once per month that should both be kept for 1 day. Creating or editing a plan like this fails with: 

```
znapzendzetup create --recursive SRC '1day=>1day,1day=>1month' storage/pv DST '2month=>1d,6month=>1month' root@10.0.0.1:storage/cluster/pv
ERROR: retention time '1days' already specified
```

Does this work like intended?

**Comment by moetiker** [comment]
I think yes, if you have every day for 1 month a copy it does not make sense to keep them just for one day

**Comment by simt2** [comment]
I might very well be wrong, but to my current understanding of znapzend and its plans the above configuration would resolve to this:

* Snapshots are made daily and additionally once a month
* The daily snapshots are kept for one day on the source and for two months on the destination
* The monthly snapshots are kept for one day at the source and for six months on the destination
* Once a month, the daily is redundant with the monthly

It would not make sense to me to keep the monthly snapshot two instead of one day at the source as they are mainly for archival purposes.

**Comment by oetiker** [comment]
that will not work ... since backups are differential ... you have to keep a sufficient number of snapshots locally to cover the backup interval ... but since zfs does blocklevel snapshots this should not be much of a problem space wise
