### ISSUE TITLE
Issues with refreshing znapzend during any operation

### ISSUE THREAD

**Issue by gusioo** [oetiker/znapzend#284]
I observed that refreshing znapzend during any operation may be problematic

e.g.

1. When synchronization is in progress...

```
[Mon Aug 21 12:39:12 2017] [info] found a valid backup plan for 
zfspool/source...
[Mon Aug 21 12:40:00 2017] [debug] snapshot worker for zfspool/source 
spawned (31081)
[Mon Aug 21 12:40:00 2017] [info] creating snapshot on zfspool/source
[Mon Aug 21 12:40:01 2017] [info] running post snapshot command on 
zfspool/source
[Mon Aug 21 12:40:03 2017] [debug] snapshot worker for zfspool/source 
done (31081)
[Mon Aug 21 12:40:03 2017] [debug] send/receive worker for 
zfspool/source spawned (31293)
[Mon Aug 21 12:40:03 2017] [info] starting work on backupSet zfspool/source
[Mon Aug 21 12:40:03 2017] [debug] sending snapshots from zfspool/source 
to root@192.168.251.59:zfspool/destination
```

2. ... and znapzend is being refreshed ....

```
[Mon Aug 21 12:40:10 2017] [info] refreshing backup plans...
[Mon Aug 21 12:40:10 2017] [info] found a valid backup plan for 
zfspool/source...
[Mon Aug 21 12:40:55 2017] [info] refreshing backup plans...
[Mon Aug 21 12:40:56 2017] [info] found a valid backup plan for 
zfspool/source...
[Mon Aug 21 12:41:01 2017] [info] refreshing backup plans...
[Mon Aug 21 12:41:02 2017] [info] found a valid backup plan for 
zfspool/source...
```

3. ... then I guess another process responsible for sending snapshot is 
executed which causes following errors:

```
[Mon Aug 21 12:45:00 2017] [debug] snapshot worker for zfspool/source 
spawned (7229)
[Mon Aug 21 12:45:00 2017] [info] creating snapshot on zfspool/source
[Mon Aug 21 12:45:01 2017] [info] running post snapshot command on 
zfspool/source
[Mon Aug 21 12:45:08 2017] [debug] snapshot worker for zfspool/source 
done (7229)
[Mon Aug 21 12:45:08 2017] [debug] send/receive worker for 
zfspool/source spawned (7746)
[Mon Aug 21 12:45:08 2017] [info] starting work on backupSet zfspool/source
[Mon Aug 21 12:45:08 2017] [debug] sending snapshots from zfspool/source 
to root@192.168.251.59:zfspool/destination
[Mon Aug 21 12:45:19 2017] [warn] ERROR: cannot send snapshots to 
zfspool/destination on root@192.168.251.59
[Mon Aug 21 12:45:19 2017] [debug] cleaning up snapshots on 
root@192.168.251.59:zfspool/destination
[Mon Aug 21 12:45:19 2017] [warn] ERROR: suspending cleanup source 
zfspool/source because at least one send task failed
[Mon Aug 21 12:45:20 2017] [info] done with backupset zfspool/source in 
12 seconds
[Mon Aug 21 12:45:20 2017] [debug] send/receive worker for 
zfspool/source done (7746)
```

```
# zfs send zfspool/source@autosnap_2017-08-21-124500|ssh -o 
StrictHostKeyChecking=no -o batchMode=yes -o ConnectTimeout=30 
root@192.168.251.59 zfs recv -F zfspool/destination
cannot receive new filesystem stream: dataset is busy
warning: cannot send 'zfspool/source@autosnap_2017-08-21-124500': signal 
received
```

Above error is a conseqence of first synchronization that is still in 
progress...

The same apply for creating snapshots (then you get snapshot already 
exists error) and deleting snapshots (then you get snapshot does not 
exist error).

Any plans or ideas to handle this?

**Comment by oetiker** [comment]
hmmm the idea is for the current send task to complete before the new one gets launched ... odd

**Comment by gusioo** [comment]
It works as expected when I do not refresh (by sending HUP signal) znapzend. 

It looks like there's another worker executed and it does not check if the previous one is still in progress.

BTW, I'm using version 0.14.1.

**Comment by gusioo** [comment]
Hi,

My supposition is that function **$refreshBackupPlans** just re-reads zfs properties without taking in consideration current pids of workers (snap_pid and send_pid are cleared) so the new workers are executed.

May it be correct?

**Comment by oetiker** [comment]
on receiving SIGHUP, the following code is executed, https://github.com/oetiker/znapzend/blob/21d63948943a07edc8b379379384bc24fe4ce0c7/lib/ZnapZend.pm#L629

it just starts 'fresh' normally this should have the effect of letting old tasks run their course and new tasks being launched at the regular interval ... but if a task takes longer than the regular interval, then the symptom you describe would be observed ... to cater for that a more elaborate signal handler would be required ...
