### ISSUE TITLE
"Chain replication" feature

### ISSUE THREAD

**Issue by gusioo** [oetiker/znapzend#285]
Hi,

I want to ask about possibility to implement a "chain replication" for example:

**NODE_A** creates and sends snapshots to **NODE_B**  but **NODE_B** does not create any new snapshots only sends existing ones to **NODE_C**.

What do you think about this idea and do you consider it worth to implement?

**Comment by oetiker** [comment]
hmmm :) I don't have a use case for this, but if you do, by all means, create a PR. I guess the challenge will be on how to keep track of the configuration for such a case ...
