### ISSUE TITLE
znapzendzetup delete is confusing and unreliable

### ISSUE THREAD

**Issue by jrdemasi** [oetiker/znapzend#286]
Why not just accept "none" or "-" as parameters to disable a destination?  At least this can be modified without invoking znapzendzetup at all, is clearer, and less risky as a whole.  

This would greatly benefit anyone using znapzend in the context of configuration management like Puppet or Ansible.  I've found that if you type znapzendzetup delete --dst=<key> <filesystem> and get the key wrong (still not sure what key describes), it may wipe out the entire configuration.  This is less than desirable.

**Comment by jrdemasi** [comment]
`root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.colorado.edu/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=dst_0 z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.colorado.edu/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=dst_0_plan z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.colorado.edu/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=0 z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
root@hostname:/root# 
`

**Comment by jrdemasi** [comment]
`
root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.domain.tld/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=dst_0 z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.domain.tld/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=dst_0_plan z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
*** backup plan: z2pool-1/poolname ***
dst_0           = backupdest:z2pool-1/Backups/hostname.domain.tld/poolname
dst_0_plan      = 3days=>1hour,10days=>1day
enabled         = on
mbuffer         = off
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = /usr/local/bin/sleepytime.sh
recursive       = off
src             = z2pool-1/poolname
src_plan        = 4days=>1hour,5days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

root@hostname:/root# znapzendzetup delete --dst=0 z2pool-1/poolname
root@hostname:/root# znapzendzetup list z2pool-1/poolname
root@hostname:/root# 

`

**Comment by jrdemasi** [comment]
I can see now that setting the value to a "-" just removes the property, seemingly.  I can't find this in the documentation, though, and the above still seems like an issue with the delete functionality.

**Comment by oetiker** [comment]
`znapzendzetup delete --dst=0 z2pool-1/poolname`

dest is the name of your destination ... the prefix 'dst_' in the zfs properties is there for namespace separation purposes.

**Comment by oetiker** [comment]
What might have been helpful in your case if  `ZnapZend::ZFS::deleteBackupDestination`  complained when trying to remove a non existing destination ... fancy doing a patch for that ?

**Comment by jrdemasi** [comment]
Well, it's not just that, but also worth noting that when I put in the
backup destination, it still doesn't actually remove it.

I'm not really one for Perl but I'll at least take a look.

**Comment by jrdemasi** [comment]
@oetiker Can confirm that your command doesn't just remove the destination, but the entire configuration.
