### ISSUE TITLE
Please allow some SSH configuration

### ISSUE THREAD

**Issue by nodens** [oetiker/znapzend#287]
Hi,

in some cases, it's not possible to change ssh configuration of root user to select, for instance, ssh key to use (Joyent Triton in our case, it can be configured but it will be lost at every boot).

It would be nice to allow some configuration of the ssh connection in znapzend.

Cheers !

**Comment by oetiker** [comment]
by all means, if you have a cool idea for that please create a PR ... since we are mostly working on omnios, our own needs do not include this feature ...
