### ISSUE TITLE
znapzend flags not read from ZFS properties?

### ISSUE THREAD

**Issue by jallakim** [oetiker/znapzend#288]
Hi,

According to [this](https://github.com/oetiker/znapzend/blob/master/doc/znapzend.pod), it says that znapzend gets it's configuration from ZFS properties, but this is not true for some of the flags; for example `--features`. Is this intentional, or just somewhat "unclear" documentation?

**Comment by oetiker** [comment]
this is intentional, as we assumed these to be global flags that depend on the setup of your system and not on an individual fileset ... but if you see other applications what would require different settings ... feel free to create a PR.
