### ISSUE TITLE
znapzendzetup does not store '--pfexec|sudo' flag?

### ISSUE THREAD

**Issue by jallakim** [oetiker/znapzend#289]
Hi,

Maybe somewhat related to #288, but is it intentional that you have to specify the `--pfexec|sudo` flag for each time you enter the command, even though the different configurations was created using the `--pfexec|sudo` flag in the first place? Wouldn't it be better to store the flag in the ZFS properties, and then use that property for each configuration, so that you don't have to use every time you use `znapzendzetup`, `znapzendztatz` or `znapzend`?

This approach would also make it possible to have some DST with sudo, and some without (currently it's all or nothing).

**Comment by oetiker** [comment]
if you want to provide a patch for configuring this per-fileset, by all means, create a PR ... also then you might want to consider makeing it possible to define whether it is used locally or at the remote end ... maybe configurability per dataset only makes sense on the remote end ...
