### ISSUE TITLE
Compilling fails on omniosce

### ISSUE THREAD

**Issue by budachst** [oetiker/znapzend#290]
Hi,

just tried to compile/install znapzend on omniosce and got stuck at the following Perl module:

List::Util ()

The build.log shows this:

cp lib/List/Util.pm blib/lib/List/Util.pm
cp lib/Scalar/Util.pm blib/lib/Scalar/Util.pm
cp lib/Sub/Util.pm blib/lib/Sub/Util.pm
cp lib/List/Util/XS.pm blib/lib/List/Util/XS.pm
Running Mkbootstrap for List::Util ()
chmod 644 "Util.bs"
"/usr/perl5/5.24.1/bin/i386/perl" "/usr/perl5/5.24.1/lib/ExtUtils/xsubpp"  -typemap "/usr/perl5/5.24.1/lib/ExtUtils/typemap"  ListUtil.xs > ListUtil.xsc && mv ListUtil.xsc ListUtil.c
gcc -c    -D_REENTRANT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TS_ERRNO -fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE64_SOURCE -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV -O3    -DVERSION=\"1.45\"  -DXS_VERSION=\"1.45\" -fPIC "-I/usr/perl5/5.24.1/lib/i86pc-solaris-thread-multi-64int/CORE"  -DPERL_EXT ListUtil.c
In file included from ListUtil.xs:7:0:
/usr/perl5/5.24.1/lib/i86pc-solaris-thread-multi-64int/CORE/perl.h:689:23: fatal error: sys/types.h: No such file or directory
compilation terminated.
*** Error code 1
make: Fatal error: Command failed for target `ListUtil.o'
Current working directory /root/Software/znapzend-0.17.0/thirdparty/work/1505038250.3531/Scalar-List-Utils-1.45
-> FAIL Installing Scalar::Util failed. See /root/Software/znapzend-0.17.0/thirdparty/work/1505038250.3531/build.log for details. Retry with --force to force install it.
Searching Test::Harness on mirror file:///root/Software/znapzend-0.17.0/thirdparty/CPAN ...
Test::Harness is up to date. (3.36_01)
Searching TAP::Parser on mirror file:///root/Software/znapzend-0.17.0/thirdparty/CPAN ...
Already tried Test-Harness-3.36. Skipping.

Actually gmake seems to complain that it cannot find sys/types.h:

In file included from ListUtil.xs:7:0:
/usr/perl5/5.24.1/lib/i86pc-solaris-thread-multi-64int/CORE/perl.h:689:23: fatal error: sys/types.h: No such file or directory

However, I have installes the developer/gcc51 pkg, does it need something else?

**Comment by oetiker** [comment]
try 

`pkg install system/header`
