### ISSUE TITLE
znapzendzetup import unable to handle export

### ISSUE THREAD

**Issue by dylanPowers** [oetiker/znapzend#291]
I've been messing with the import/export feature of znapzendzetup and I have found that import can't handle the config that gets exported.
Some example errors:
`ERROR: property post_znap_cmd: executable 'off' does not exist or can't be executed`  
`ERROR: timestamp format not valid. check your syntax`
`ERROR: property enabled is not valid on dataset`

Example exported config:
```
enabled=on
mbuffer=off
mbuffer_size=1G
post_znap_cmd=off
pre_znap_cmd=off
recursive=off
src=rpool/docker
src_plan=1days=>15minutes,1weeks=>1days,1months=>1weeks
tsformat=%Y-%m-%d-%H%M%S
zend_delay=0
```

**Comment by moetiker** [comment]
Is this not a cut/past problem or newlines  dos/unix "^M"

**Comment by dylanPowers** [comment]
This is on linux. I exported straight to the file using i/o redirection. And did the same importing on the same machine.
I'm digging a little into the code myself to see what's up and see if I can debug it. My guess is some sort of encoding issue

**Comment by dylanPowers** [comment]
So you got it, for some reason export is outputting carriage returns:
```
$ cat -vet plan 
enabled=on^M$
mbuffer=off^M$
mbuffer_size=1G^M$
post_znap_cmd=off^M$
pre_znap_cmd=off^M$
recursive=off^M$
src=rpool/docker^M$
src_plan=1days=>15minutes,1weeks=>1days,1months=>1weeks^M$
tsformat=%Y-%m-%d-%H%M%S^M$
zend_delay=0^M$
```

**Comment by dylanPowers** [comment]
Ugh, I was running this inside a docker container, and it's just docker being dumb
