### ISSUE TITLE
Znapzend recursive conflict bug

### ISSUE THREAD

**Issue by dylanPowers** [oetiker/znapzend#296]
Let's say I have the following directory structure:
rpool/var
rpool/var/tmp
rpool/var/lib
rpool/var/cache

Now by default, I want everything in rpool/var to have a relatively short backup lifetime so I set the backup rules of rpool/var to be recursive. But I want rpool/var/lib to have long lived backups, so I set that up separately. What ends up happening is a weird conflict of rules and an undefined behavior caused by the usage of zfs snapshot/destroy -r.

The workaround of course is to manually set up each individual filesystem without any recursive property.

I think what znapzend should be doing is manually recursing through the zfs filesystems rather than using the recursive commands and make use of the builtin inheritance of zfs properties to know which rules to follow.

Here's what I think should be changed:
* ~~Recursive should be a property of how znapzendzetup should behave when setting up a src rather than a property of znapzend~~
  * ~~Specifically, it should manually set `org.znapzend:enabled=on` on each descendant filesystem~~
  * Nah, some people expect recursive to mean that future child datasets will also be included in the backup plan
* Don't inherit org.znapzend:enabled or org.znapzend:recursive
* Allow all other properties to inherit

**Comment by oetiker** [comment]
care todo a test implementation of your idea ?

**Comment by dylanPowers** [comment]
I'm thinking that at some point I want to try this out if you don't see any obvious issues I'm going to encounter. I figured I'd get some feedback on the idea before dumping a PR here. I just have no idea when I'll get around to it

**Comment by oetiker** [comment]
I don't see anython beyond the problem outlines above
