### ISSUE TITLE
Missed backups for daylight savings or TZ changes

### ISSUE THREAD

**Issue by dylanPowers** [oetiker/znapzend#297]
When timezone related backward jumps in time occur, znapzend will try and fail to overwrite old snapshots. Meanwhile, no new snapshots will be made. I think by default, the timezone's offset should be appended to the string:
```
%z | ISO 8601 offset from UTC in timezone (1 minute=1, 1 hour=100)If timezone cannot be determined, no characters | +100
```
Or just default to UTC?

**Comment by oetiker** [comment]
you can configure the string used by znapzend ...

**Comment by oetiker** [comment]
:) PR is welcome ... note though not all systems may support %z

**Comment by jimklimov** [comment]
Code is merged, should the issue be closed?
