### ISSUE TITLE
Resume large transfers

### ISSUE THREAD

**Issue by aarononeal** [oetiker/znapzend#298]
Backing up large datasets to the cloud can be really hard to do without resumable transfers. How about adding support for the `-s` option on receive and checking for `receive_resume_token` before send?

**Comment by aarononeal** [comment]
I added PR #299 which handles the receive side of this.

It's useful on its own since a partial transfer prevents future sends and allows for manual recovery:
```
  zfs get receive_resume_token tank/test
  zfs send -t <token> | zfs receive -s tank/test
```

Ideally a subsequent PR would handle the above recovery automatically by checking for a resume token to determine whether to initiate a resume or a regular send. That's beyond what I can do in the codebase today--any takers?

**Comment by hakong** [comment]
Any work being done on this? Would be very good to have resumable transfers.

**Comment by oetiker** [comment]
I don't think so

**Comment by psy0rz** [comment]
ZFS-autobackup does this automaticly. Check it out at https://github.com/psy0rz/zfs_autobackup

I would suggest checking the latest 3.1 beta. (its reliable and soon to be released.)
