### ISSUE TITLE
zfs receive -F cannot be used to destroy an encrypted filesystem

### ISSUE THREAD

**Issue by sjau** [oetiker/znapzend#302]
Hi there

pretty new to ZFS and just encryption from master. Znapzend was recommended to me for creating and sending snapshots to backup server so I gave it a try. Howerver it fails because zfs receives -F cannot be used to destroy an encrypted filesystem.

I posted the issue in the zol repo already:  https://github.com/zfsonlinux/zfs/issues/6793

So, the reason for the -F flag is to reset to the latest snapshot. However since they are for backup only for me I tend to think a reset isn't necessary. Normal send/receive withtout -F flag works just fine.

So I'd like to propose an option to omit the -F flag if possible.

**Comment by oetiker** [comment]
we always consider PRs ... by all means!

**Comment by GabrieleV** [comment]
Hello,
I'm facing the same issue: how can I use a remote encrypted destination ?

**Comment by sjau** [comment]
I wrote my own tool meanwhile.
