### ISSUE TITLE
[warn] ERROR: snapshot(s) exist on destination, but no common found on source and destination clean up destination". 

### ISSUE THREAD

**Issue by kroem** [oetiker/znapzend#303]
I'm getting " [warn] ERROR: snapshot(s) exist on destination, but no common found on source and destination clean up destination". 

Seems like I had some problems on a remote server, and now the version of those snapshots are older than the ones on my main server - do I really need to remove the old ones before znapzend creates new ones?

**Comment by oetiker** [comment]
yes ... if there is no common snapshot between src and dest then there is no way to 'link up' again.
