### ISSUE TITLE
blocked on the first snapshot send

### ISSUE THREAD

**Issue by infologeek** [oetiker/znapzend#304]
Hello
I installed znapzend on debian 9.1 (proxmox).

My plan:
znapzendzetup` create --recursive --mbuffer = / usr / bin / mbuffer --mbuffersize = 1G --tsformat = '% d-% m-% Y-% H% M% S' SRC '7d => 30min' rpool / data / vm-100-disk-1 DST '7d => 30min' root@192.168.1.150: zsjc / backup-vm-win10

after: znapzend --daemonize

Snapshots are done locally without problems but sends the first snapshot never ends.

sh -c zfs send rpool / data / vm-100-disk-1 @ 06-12-2017-083000 | ssh -o batchMode = yes -o ConnectTimeout = 30 'root@192.168.1.150' '/ usr / bin / mbuffer -q -s 128k -W 60 -m 1G | zfs recv -f zsjc / backup-vm-win10 '

ssh -o batchMode = yes -o ConnectTimeout = 30 root@192.168.1.150 / usr / bin / mbuffer -q -s 128k -W 60 -m 1G | zfs recv -f zsjc / backup-vm-win10

So no snapshot on the remote server.

log:

# cat /var/log/znapzend.log
[Wed Dec 6 08:24:55 2017] [info] znapzend (PID = 8869) starting up ...
[Wed Dec 6 08:24:55 2017] [info] refreshing backup plans ...
[Wed Dec 6 08:24:55 2017] [info] found a valid backup map for rpool / data / vm-100-disk-1 ...
[Wed Dec 6 08:24:55 2017] [info] znapzend (PID = 8870) initialized - resuming normal operations.
[Wed Dec 6 08:30:00 2017] [debug] snapshot worker for rpool / data / vm-100-disk-1 spawned (14566)
[Wed Dec 6 08:30:00 2017] [info] creating recursive snapshot on rpool / data / vm-100-disk-1
[Wed Dec 6 08:30:01 2017] [debug] worker snapshot for rpool / data / vm-100-disk-1 done (14566)
[Wed Dec 6 08:30:01 2017] [debug] send / receive worker for rpool / data / vm-100-disk-1 spawned (14658)
[Wed Dec 6 08:30:01 2017] [info] starting work on backupSet rpool / data / vm-100-disk-1
[Wed Dec 6 08:30:01 2017] [debug] sending snapshots from rpool / data / vm-100-disk-1 to root@192.168.1.150: zsjc / backup-vm-win10
[Wed Dec 6 09:00:00 2017] [debug] snapshot worker for rpool / data / vm-100-disk-1 spawned (2646)
[Wed Dec 6 09:00:00 2017] [info] creating recursive snapshot on rpool / data / vm-100-disk-1
[Wed Dec 6 09:00:01 2017] [debug] worker snapshot for rpool / data / vm-100-disk-1 done (2646)
[Wed Dec 6 09:00:01 2017] [info] previous send / receive process on rpool / data / vm-100-disk-1 still running! skipping this round ...

Sends infinite the first snapshot. Always still running.

Of course I have done several times by removing the plan, snapshot sources, the remote zvol but each time the same problem.

If you have a suggestion.

Thank you

**Comment by hadfl** [comment]
how big is the dataset you are about to transfer? depending on the size (and bandwith) it can take a while to transfer the initial (full) snapshot.

ever tried a send/recv "by hand"? (adding `-v` to the send command so you see the progress). so you can rule out a zol send/recv issue.

**Comment by infologeek** [comment]
Hello,

In fact the remote server is a server on the local network in gigabyte! (192.168.1.150)
Since I made my post, the size has increased with the snapshots that are done on the source server but the first snapshot is still being sent !!!!

# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
rpool                     65.4G   834G    96K  /rpool
rpool/ROOT                1.74G   834G    96K  /rpool/ROOT
rpool/ROOT/pve-1          1.74G   834G  1.74G  /
rpool/data                56.1G   834G    96K  /rpool/data
rpool/data/vm-100-disk-1  56.1G   834G  46.3G  -
rpool/swap                7.44G   840G   780M  -

Tu peux voir avec la date sur le serveur source: 

# ps aux | grep zfs

root      3104  0.0  0.0  12788   976 pts/0    S+   07:17   0:00 grep zfs
root     14662  0.0  0.0   4292   616 ?        S    Dec06   0:00 sh -c zfs send rpool/data/vm-100-disk-1@06-12-2017-083000|ssh -o batchMode=yes -o ConnectTimeout=30 'root@192.168.1.150' '/usr/bin/mbuffer -q -s 128k -W 60 -m 1G|zfs recv -F zsjc/backup-vm-win10'
root     14664  0.0  0.0  49552  6368 ?        S    Dec06   1:17 ssh -o batchMode=yes -o ConnectTimeout=30 root@192.168.1.150 /usr/bin/mbuffer -q -s 128k -W 60 -m 1G|zfs recv -F zsjc/backup-vm-win10

On the destination server, no snapshot.
I will try to do it manually as you advised me.

thank you
