### ISSUE TITLE
znapzend.service points to wrong location of installation

### ISSUE THREAD

**Issue by averyfreeman** [oetiker/znapzend#305]
Hi!  Thanks for the great program.  I have installed it on my Arch laptop with ZFS root.                                                            

I noticed when `# make install` installed znapzend, it placed executables in `/opt/znapzend-0.17.0/bin/`

However, the init service packaged in the git repo points to: `ExecStart=/usr/local/bin/znapzend`

Is this expected behavior?  Is there something I missed in the installation where symlinks are installed?

Here's my original copy of znapzend.service:

description "znapzend"

respawn

start on [2345]
stop on runlevel [06]

expect fork
reload signal HUP

exec /usr/local/bin/znapzend --daemonize
[avery@ant520 init]$ cat znapzend.service
[Unit]
Description=ZnapZend - ZFS Backup System
Documentation=man:znapzend
After=zfs-import-cache.service
After=zfs-import-scan.service

[Service]
ExecStart=/usr/local/bin/znapzend
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
\# might be neccessary on low power systems
\# Nice=19
\# IOSchedulingClass=2
\# IOSchedulingPriority=7

[Install]
WantedBy=multi-user.target

Here's the version I edited for my laptop:

[Unit]
Description=ZnapZend - ZFS Backup System
Documentation=man:znapzend
After=zfs-import-cache.service
After=zfs-import-scan.service

[Service]
ExecStart=/opt/znapzend-0.17.0/bin/znapzend
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
\# might be neccessary on low power systems
Nice=19
IOSchedulingClass=2
IOSchedulingPriority=7

[Install]
WantedBy=multi-user.target

Did I do that right?

**Comment by jimklimov** [comment]
Hello, the "original copy" looks like an upstart manifest, not as a systemd service (unlike the second block in your paste).

Indeed, until recently the `/usr/local/bin` paths were hardcoded there, and should now be generated to correspond to configured values since PRs #340 and #348
