### ISSUE TITLE
Skip replication on DST using ---pre-snap-command exit code

### ISSUE THREAD

**Issue by GabrieleV** [oetiker/znapzend#307]
I use znapzend on my notebook, replicating on our LAN server.
When I am outside of our office, replication is aborted because the LAN server is unreachable. This is good.
When I connect via VPN to our office LAN, I want to skip replicating to avoid network congestion.
Is it possible to skip replication based on some condition ?
I think about writing a script that give an exit code based on network location.

Thank you,
GV

**Comment by atj** [comment]
This functionality was implemented in PR #316. Running znapzend with the `--skipOnPreSendCmdFail` option will cause replication to be skipped if the destination pre-send-command returns a non-zero exit code.
