### ISSUE TITLE
Can't prune old snapshots; "Argument list too long"

### ISSUE THREAD

**Issue by asciiphil** [oetiker/znapzend#308]
I have a system that built up more than 32,000 snapshots over the course of several months.  (Local snapshots were made every five minutes, but sending them to the remote system was failing, so the local snapshots were never pruned.)

Once znapzend was willing to prune the snapshots, it was unable to do so because there were too many.  It would try to run a `zfs destroy` command with every snapshot listed in the command line.  That fails on my system with:

    Can't exec "zfs": Argument list too long at /opt/znapzend/lib/ZnapZend/ZFS.pm line 276.

znapzend should be able to split up the list of snapshots to be destroyed in order to stay under the system's command line limit.  In my searching, I couldn't find a consistent way to dynamically determine the system's current limits, but POSIX requires at least 4096 characters, so that might work as a "guaranteed to work anywhere" limit.

I'm running znapzend 0.17.0 on a Scientific Linux 6.9 system with ZFS on Linux 0.7.3.  (Perl is up to date for SL 6.9 with version 5.10.1.)

**Comment by oetiker** [comment]
in oracle mode it will destroy them individually I think ...

**Comment by oetiker** [comment]
but you can also destroy them by hand there is no magic to what znapzend does

**Comment by asciiphil** [comment]
I've been destroying them by hand, but I want to preserve the ones that znapzend wants to preserve (because of my snapshot retention definitions).  I've been running znapzend in debug mode and copying parts of its `zfs destroy` command to destroy chunks of snapshots at a time.  This has been working, but it's tedious to do it for tens of thousands of snapshots.

I turned on Oracle mode and that seems to be working.  I think it'd still be nice to not have znapzend hit a system's command line limit (or deal gracefully with situations where it does), but the Oracle mode workaround shifts this from a regular-priority bug to wishlist-priority for me.

**Comment by Harvie** [comment]
I have similar problem:

```
Apr 07 06:22:21 virt1 znapzend[635]: cleaning up snapshots on root@example.net:tank/backup/virt1
Apr 07 06:22:21 virt1 znapzend[28360]: Can't exec "ssh": Argument list too long at /opt/znapzend-0.19.0/lib/ZnapZend/ZFS.pm line 276.
Apr 07 06:22:21 virt1 znapzend[635]: ERROR: cannot destroy snapshot(s) root@example.net:tank/backup/virt1@2019-04-03-200800
Apr 07 06:22:30 virt1 znapzend[11960]: snapshot worker for tank spawned (28383)
Apr 07 06:22:30 virt1 znapzend[28383]: creating recursive snapshot on tank
Apr 07 06:22:32 virt1 znapzend[11960]: snapshot worker for tank done (28383)
```

I think this even caused whole replication of affected datasets to stop working...

I think znapzend should limit argument count and break the single command to multiple shorter commands

**Comment by SlothOfAnarchy** [comment]
I had the same problem after some 30000 snapshots accumulated. I can confirm that `--features=oracleMode` removes them individually (and changes no other behaviour). I called znapzend manually with this flag and resumed using the systemd service afterwards.

**Comment by jimklimov** [comment]
Docs update in #512 takes this suggestion into account, thanks ;)

**Comment by Harvie** [comment]
@jimklimov It is nice to have this issue documented. But i really hope this is not the only fix that we will get :-)

**Comment by jimklimov** [comment]
Acknowledging a problem is the first step to fixing ;)

I suppose something could be done about catching the particular error about
command line too long and reverting to oracleMode for this run...

**Comment by oetiker** [comment]
note that Mojo subprocesses are a good first step ...

**Comment by jimklimov** [comment]
Good point, don't think they are used in Git but could be here.

**Comment by Harvie** [comment]
bump

**Comment by jimklimov** [comment]
@Harvie : I am not sure bumping the issue to keep it afloat would help much (well, having it visible as recently relevant *is* useful) until someone scratches the its to implement the automatic `oracleMode` perhaps in a way similar to one proposed above. For others, it is usually a one-time discovery of the option to set into their service config and forget for years...
