### ISSUE TITLE
compiling fails on Linux Mint 18.3

### ISSUE THREAD

**Issue by mrdrthom** [oetiker/znapzend#310]
same problem as issue #290 but on Linux Mint 18.3 (derived from Ubuntu 16.04).  

the build.log shows missing sys/types.h :

x86_64-linux-gnu-gcc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.45\" -DXS_VERSION=\"1.45\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE"  -DPERL_EXT ListUtil.c
In file included from ListUtil.xs:7:0:
/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/perl.h:701:23: fatal error: sys/types.h: No such file or directory
compilation terminated.

**Comment by mrdrthom** [comment]
this was fixed with: sudo apt-get install build-essential

**Comment by marwey** [comment]
@oetiker Maybe it's worth adding this to the readme? Helped me on Ubuntu as well. Tx!

**Comment by oetiker** [comment]
PR welcome !
