### ISSUE TITLE
auto detect mbuffer?

### ISSUE THREAD

**Issue by testbird** [oetiker/znapzend#311]
It would be nice if znapzend could auto detect mbuffer like https://github.com/cythoning/pyznap ?

And  if available, use mbuffer without much configuration (mem detect, good defaults). Otherwise print a hint to install mbuffer.

**Comment by Harvie** [comment]
Can i just use `mbuffer=mbuffer` instead of `mbuffer=/usr/bin/mbuffer` so that it would at least automaticaly find mbuffer in `$PATH` ?

**Comment by Harvie** [comment]
bump
