### ISSUE TITLE
Docs: first timer friendlyness

### ISSUE THREAD

**Issue by testbird** [oetiker/znapzend#312]
Found this to be a really nice package, so I thought I report the little stumble points I had when I read the README.md.

1) The peculiar spelling "inztructionz" didn't appeal all too well when looking to understand the software.

2) To explain the configuration nicely, may be add a little more info than refering to the command line tool syntax.

For example, say that the authoritative configuration is saved within ???, and show have an elegant minimal example. Something along the lines of  of importing a more human readable configuration (if possible):

```
# ~/znapzend.inital-config

src        = z2pool-1/poolname
src_plan   = 4days=>1hour, 5days=>1day

dst_0      = backupdest:z2pool-1/Backups/hostname.domain.tld/poolname
dst_0_plan = 3days=>1hour, 10days=>1day
```
`znapzendzetup import --write ~/znapzend.initial-config`

Or a shell script.

3) Explain znapzend.service file usage

**Comment by oetiker** [comment]
if you were to create a PR with your improvements, I would be glad to merge it!

**Comment by testbird** [comment]
Ok, please correct where necessary and apply.

**Comment by testbird** [comment]
I don't know about the "znapzend.service file usage"
