### ISSUE TITLE
Restoring a server backed up using ZnapZend

### ISSUE THREAD

**Issue by garethhowell** [oetiker/znapzend#319]
I've been using ZnapZend to keep a rolling backup of my SmartOS based home server on another SmartOS server in the garage. It's been running fine for ages, but the time has come to make use of the backups.

My main server ran out of disk space and it wasn't simply a job of putting bigger disks and re-silvering: I had to change the raidz configuration. Thus I now need to rebuild the main server from the data on the backup.

The main server's (deneb) ZnapZend job is single recursive job of the entire zones pool, so the backup (eridani) has a dataset hierarchy starting at zones/backup/deneb/zones.

I've cloned eridani's pool on to an external eSATA device and connected that to deneb as zznew, but how do I restore the backup hierarchy when zones is in use? I initially tried booting into system recovery mode (so that zones wasn't mounted) and then doing a zfs send/recv, but the resulting system failed to boot.

Is there a recipe?

**Comment by oetiker** [comment]
I'm afraid I can not help you with this on smartos, since I use omnios and would be faced with a different set of problems ... I suggest you ask on the smartos mailinglist ... restoring from a snapshot after all is not a znapzend specific problem.
