### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by UnConundrum** [oetiker/znapzend#326]
I'm having problems installing on Ubuntu 17.10.  Make install has the following errors:

/usr/bin/install: './ZnapZend.pm' and '/opt/znapzend-0.17.0/lib/./ZnapZend.pm' are the same file
Makefile:275: recipe for target 'install-nobase_dataDATA' failed
make[2]: *** [install-nobase_dataDATA] Error 1
make[2]: Leaving directory '/opt/znapzend-0.17.0/lib'
Makefile:348: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/opt/znapzend-0.17.0/lib'
Makefile:473: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

Any help would be appreciated

**Comment by oetiker** [comment]
NEVER NEVER NEVER try to install znapzend (or any software) into the same directory where you unpacked the source ...

**Comment by UnConundrum** [comment]
Sorry, didn't realize the meaning of the --prefix switch and I just copied your suggested commands  verbatim.
