### ISSUE TITLE
Exclude filesystems when recursive

### ISSUE THREAD

**Issue by tatarenko** [oetiker/znapzend#328]
I want to exclude filesystems with temp files when making backup with znapzend.
Is it possible to make it?
If not, could you please add exclude option to znapzendzetup?

**Comment by oetiker** [comment]
the trick with recursive snapshots is that they are consistent there is no option for excluding a particular fileset in the zfs command ... what would be possible, is to somehow exclude a fileset from being transfered to the destination as these operations are done per fileset ... your PRs are welcome ...

**Comment by Dacesilian** [comment]
Hello, this requirement is here again and still not solution exists. @oetiker , please, could it be done simply as to 1. if dataset is excluded, do not copy it, then 2. skip checking successful copying and 3. delete snapshots normally when planned ? It would be great to have this possibility to exclude one child dataset from backup. Thanks.
