### ISSUE TITLE
How to use --compressed on send command

### ISSUE THREAD

**Issue by jloms** [oetiker/znapzend#334]
I see with the new 0.18 version, the compression send option ( -c in zfs on linux) is now present in the scripts.
Is there a way to activate this feauture via znapzendzetup, or do I need to change the script:
has compressed              => sub { 1 };

Thanks for your great job.

**Comment by oetiker** [comment]
that would be `--feature=compressed`

**Comment by STRML** [comment]
FYI: The only way I could get this to activate reliably was to add `--features=sudo,compressed` to the init script for znapzend. Adding `features=compressed` to the config in znapzendzetup did not work.

**Comment by chaerle** [comment]
> 
> 
> that would be `--feature=compressed`

This option does not worl in znapzendzsetup.
