### ISSUE TITLE
Do I have to use mbuffer?

### ISSUE THREAD

**Issue by gusioo** [oetiker/znapzend#335]
Hi,

I have a question about mbuffer in znapzend: could anyone tells me when I must use mbuffer and what determines the size of mbuffer? Also what are the benefits and disadvantages of using mbuffer?

Best regards.

**Comment by jimklimov** [comment]
Thanks for your comment, I hopefully answered the mbuffer question while documenting my woes ;)

**Comment by gusioo** [comment]
Hi,

thanks, now it's clear.

Best regards.

**Comment by Harvie** [comment]
How bad it will get if i don't use mbuffer? My replication seems to be very slow, i don't even think that some buffer can help so much... I guess i will try enabling it...
