### ISSUE TITLE
Odd recursive behaviour 

### ISSUE THREAD

**Issue by monkiki** [oetiker/znapzend#343]
Hello, I've just started using ZnapZend and I'm not sure it this is the expected behaviour when using the recursive=on parameter. For example, I've these datasets:

- zfs-pool/container/cnt1
- zfs-pool/container/cnt2

If the **src** configuration is "zfs-pool/container" and **recursive** is on these are the snapshots created in the destination server:

- zfs-pool/znaptest/srv1
- zfs-pool/znaptest/srv1@2018-05-01
- zfs-pool/znaptest/srv1/cnt1
- zfs-pool/znaptest/srv1/cnt1@2018-05-01
- zfs-pool/znaptest/srv1/cnt2
- zfs-pool/znaptest/srv1/cnt2@2018-05-01

I absolutely understant these snapshots:

- zfs-pool/znaptest/srv1/cnt1@2018-05-01
- zfs-pool/znaptest/srv1/cnt2@2018-05-01

But I don't know the meaning of this one because the data is in the children datasets not in the parent one:

- zfs-pool/znaptest/srv1@2018-05-01 

Does it make sense? Do I really need a snapshot of the parent dataset?

**Comment by oetiker** [comment]
well that is how recursive snapshots in zfs work ... unless you want to change zfs, there is not much you can do about it ...

**Comment by monkiki** [comment]
Thanks for the info :)
