### ISSUE TITLE
Difficult to disable for chosen datasets

### ISSUE THREAD

**Issue by jimklimov** [oetiker/znapzend#345]
There are some datasets that I do not want to retain a history for (e.g. swap volumes, or sinks for core files).

In an older version I could set "enabled=off" via zfs (because I have no idea what `znapzendzetup disable` and `delete` do, but not the evident thing it seems).

Now it looks like ZFS parsing requires that all config items are from same source (e.g. "local" vs "inherited from ...") so this setup with just one override fails:

````
rpool/SHARED/var/crash  org.znapzend:enabled            off                                                                local
rpool/SHARED/var/crash  org.znapzend:pre_znap_cmd       off                                                                inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:src_plan           1weeks=>30minutes,2months=>1days,4months=>1weeks,10years=>1months  inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:post_znap_cmd      off                                                                inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:zend_delay         0                                                                  inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:recursive          on                                                                 inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:mbuffer            /usr/bin/amd64/mbuffer                                             inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:mbuffer_size       1G                                                                 inherited from rpool/SHARED
rpool/SHARED/var/crash  org.znapzend:tsformat           %Y-%m-%dT%H:%M:%SZ                                                 inherited from rpool/SHARED
````

In the logs (or using command-line tools) I get a random selection of znapzend required key names that are "not set on backup":

````
[ May  4 22:56:41 Executing start method ("/usr/share/znapzend/bin/znapzend --daemonize --pidfile=/dev/null"). ]
znapzend (19206) is running in the background now.
[ May  4 22:56:42 Method "start" exited with status 0. ]
May  4 22:56:55 jimoi znapzend[19206]: [ID 702911 daemon.error] ERROR: property src_plan not set on backup for rpool/SHARED/var/crash
[ May  4 22:56:55 Stopping because all processes in service exited. ]
[ May  4 22:56:55 Executing stop method (:kill). ]
````

**Comment by jimklimov** [comment]
After a closer look, it seems that `ZFS.pm` only looks for datasets where the whole set of variables is defined as "local", and does not seem to support pruning parts of a tree. So if any point is recursive and enabled, it is then so all the way down the tree - no exclusions. If I read it right...

**Comment by hadfl** [comment]
yes, you are right. znapzend worked from the beginning on like that. if recursion is enabled it won't check what's down the tree (i.e. disabled sub-datasets). there were/are plans to enhance this but no one found the time to get it implemented. if you have spare cycles to implement it and create a PR that would be great

**Comment by oetiker** [comment]
@jimklimov note though, that by enabling consistent recursive treatment you get recursive zfs snapshots ... you can't get them 'not made' since this is what zfs does ... but there could be an option for not transferring them or getting rid of them right away

**Comment by jimklimov** [comment]
Added a note for the docs in #349 then :)

As for pruning support - that was something I inherently inspected while trying to migrate away from time-slider and zfs-auto-snapshot, which lagged quite a bit for me (one core always busy with a zfssnap owned process, looping to do many `zfs list` or `zfs get` requests). So in their case - indeed, if there is a recursive config for a tree, and then exceptions to it, the script tries to recalculate the tree to things that can still be snapshot recursively with one command, and others that have to be handled one by one. I wonder if there are efficient solutions to do this - so the goal is achieved and less lags incurred (e.g. read all "local" dataset properties for the system once, as znapzend seems to do, not in a loop).

While documenting the nuance for least surprise is also a good option (e.g. this can be done, but costs you, and can be avoided by planning the layout of datasets differently), actually moving existing datasets around is often not an option...

**Comment by jimklimov** [comment]
So, the current state of affairs is documented in #349 - that there is no recursion pruning (and override?) support at this time. Still, I guess this issue should stay open as the "problem" of the lack of such feature is still there - hopefully someone (me, you, others) would at some point tackle it :)
