### ISSUE TITLE
feature request: Detailed documentation

### ISSUE THREAD

**Issue by mehanzhi** [oetiker/znapzend#347]
Hello,
 
1. I spend almost 2 days trying to figure what this quote from the documentation. 
> A plan is required both for the source and the destination datasets.

I have created a plan ONLY on my running system and put there as a destination my backup server. 
It still worked. It didn't just worked but in fact it transferred all the snapshots on this dataset even the ones not created by znapzend. 
Actually I haven't found information at all about what is source and what is destination in the context of znapzend. Now it appears that I may have a plan for my destination but on the source it may be a different plan and I can still see src_plan and dst_plan both on my source system!?!?! And when I login on my destination server I see neither source or destination plan but somehow I have the snapshots transferred there. 

2. The plan I created involved ONLY daily and weekly backups and no frequent backups but I still see znapzend doing snapshots every hour. None of that was described in the documentation. 
I spend 3 hours searching for the answer of the question "if I set a daily backup at what time the snapshots will be created and sent to the destination???" Yes - it will be once at day but will it be 3 o'clock at the night or it will be right in the middle of the business hours? Didn't see anything in the documentation and no configuration switch for this purpose. 
The plan is: 
zroot  org.znapzend:dst_a_plan     30days=>24hours,90days=>1weeks,10years=>1months  local
But I still see snapshots being created every hour. 

3. There are stuff about mbuffer in the documentation and in the man page but no further description at all - do we need them? how and why are they used? How much memory should we use for mbuffers? do we need a formula for calculation? what is the impact if we do not use, or do not specify mbuffers? 
I have used backups zfs snapshots but using manual shell scripting. And I never had to use mbuffers for this. 
There was a question posted under issues with request for further information about mbuffers but there's no answer at all. 

I am sure the behavior I have seen is quite normal and probably all according to the purpose of znapzend. But !!!please!!! write some good documentation that will make clear how to use this product. These few examples are good but there are a lot of questions every person would ask and there are no answers at all. 

Thank you

**Comment by jimklimov** [comment]
Thanks for your comment, I hopefully answered the mbuffer question while documenting my woes ;)
