### ISSUE TITLE
problems in omnios (OmniOS v11 r151026c)

### ISSUE THREAD

**Issue by natxo** [oetiker/znapzend#360]
After updating my home nas to the latest omniosce znapzed was no longer working (

ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 10d00080, needed 10f80080)

Apparently the latest omnios not cooperating with the existing znapzend libs, not a problem, I can update.

I have this other perl by pkgsrc (https://pkgsrc.joyent.com/install-on-illumos/) in my system, so I try using this:

# export PERL=/opt/local/bin/perl 
#   $ ./configure --prefix=/opt/znapzend --enable-svcinstall=/var/svc/manifest/site1

But when running gmake install :+1: 
! Installing Scalar::Util failed. See /root/znapzend/thirdparty/work/1528054349.9196/build.log for details. Retry with --force to force install it.
Test::Harness is up to date. (3.39)
gmake[1]: *** [Makefile:407: touch] Error 1
gmake[1]: Leaving directory '/root/znapzend/thirdparty'
gmake: *** [Makefile:486: all-recursive] Error 1

and in thirdparty/build.log:
Running Mkbootstrap for List::Util ()
chmod 644 "Util.bs"
"/opt/local/bin/perl" "/opt/local/lib/perl5/5.24.0/ExtUtils/xsubpp"  -typemap "/opt/local/lib/perl5/5.24.0/ExtUtils/typemap"  ListUtil.xs > ListUtil.xsc && mv ListUtil.xsc ListUtil.c
gcc -c    -D_REENTRANT -pipe -O2 -pipe -O2 -pthread -I/opt/local/include -I/usr/include -fwrapv -fno-strict-aliasing -fstack-protector-strong -I/usr/local/include -I/opt/local/include -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV -pipe -O2 -pipe -O2 -pthread -I/opt/local/include -I/usr/include    -DVERSION=\"1.45\"  -DXS_VERSION=\"1.45\" -fPIC "-I/opt/local/lib/perl5/5.24.0/x86_64-solaris-thread-multi-64/CORE"  -DPERL_EXT ListUtil.c
cc1: error: unrecognized command line option "-fstack-protector-strong"
*** Error code 1
make: Fatal error: Command failed for target `ListUtil.o'

Any tips on how to solve this?

**Comment by oetiker** [comment]
yes omnios comes with a current version of perl ... just re-install znapzend and you should be all set.

**Comment by natxo** [comment]
yes, that seems to be the problem. I have installed it with the system perl and now everything works again.

Thanks!
