### ISSUE TITLE
0.19.0 Do Not Start if no destionations are reachable

### ISSUE THREAD

**Issue by redmop** [oetiker/znapzend#363]
This should be optional as local snapshots should still be able to be taken if destinations are currently unavailable.

**Comment by oetiker** [comment]
actually ... this is not the case ... sorry I did not recall correctly, what I was referring to is this: https://github.com/oetiker/znapzend/commit/1a4e66aa9dab4f14e0ffb5a92fdf230f82c7dee7
I fixed the change log.

**Comment by redmop** [comment]
Awesome. Thanks. :)
