### ISSUE TITLE
systemd init missing znapzend.default 

### ISSUE THREAD

**Issue by redmop** [oetiker/znapzend#366]
The readme says to copy that file into /etc/default/znapzend, but I can't find that file.

**Comment by Wouter0100** [comment]
[Here](https://github.com/oetiker/znapzend/blob/915e5130e9375c2022cc561a65861b2d3a6870d2/init/znapzend.service.in) is a sample file.

**Comment by redmop** [comment]
I have that file, but not the file for /etc/default/znapzend. aka the environment file. I just noticed that it's not in the release file, but it is on github. Weird.

**Comment by oetiker** [comment]
some of the files were missing from the list in Makefile.am and therefore did not end up in the release ... I have created 0.19.1 WITH these files.
