### ISSUE TITLE
When does the first snapshot get created?

### ISSUE THREAD

**Issue by Duffyx** [oetiker/znapzend#375]
Hello,

I'd like to snapshot my root pool and back it up on my storage pool which is redundant.
I have the following config on my root pool called zroot.

znapzendzetup list

*** backup plan: zroot ***
dst_0           = storage/zroot
dst_0_plan      = 1week=>1day,1month=>1week,1year=>1month
enabled         = on
mbuffer         = /usr/local/bin/mbuffer
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = off
recursive       = on
src             = zroot
src_plan        = 1week=>1day,1month=>1week,1year=>1month
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

NOTE: if you have modified your configuration, send a HUP signal
(pkill -HUP znapzend) to your znapzend daemon for it to notice the change.

I installed the configuration to disk and started the znapzend daemon in FreeBSD.
I don't see any snapshot getting created? Are there fixed times for daily snapshots?
My highest frequency is daily and keep for a week. So maybe it is just waiting for 00:00 to take its first snapshot. Is the latter assumption correct or should znapzend create a snapshot at the moment it is started?

**Comment by moetiker** [comment]
it waits. you can test it with znapzend -d --runonce=zroot

**Comment by Duffyx** [comment]
Alright, and it waits for what exactly? 00:00h at midnight to take its first one?

**Comment by redmop** [comment]
Yes. It will take it at 00:00h on your local computer.

**Comment by moetiker** [comment]
yes

**Comment by Duffyx** [comment]
Okido thanks for helping out!
Lovely tool <3
