### ISSUE TITLE
Should I use a *blank* DST dataset ?

### ISSUE THREAD

**Issue by romainth** [oetiker/znapzend#388]
Hi !

I would like to send snapshots to a remote dataset which has already some data.
Is it a problem to use a remote dataset containing production data ?
Or should I use a remote dataset dedicated to receive snapshot ?

In other word, is there a risk to lose data in a DST dataset if it is already used ?

Thanks !

**Comment by oetiker** [comment]
if there is no shared snapshot between src and dst it will not work unless dst is empty
