### ISSUE TITLE
Documentation not clear on how SRC and DST plans relate to send/receive schedule

### ISSUE THREAD

**Issue by rcproam** [oetiker/znapzend#396]
With the following znapzend plan I was hoping to snapshot the src every 8 hours, yet only send snapshots to the dst once per day (at midnight):

*** backup plan: zpool1/vol1-nfs ***
dst_0           = root@xxx.xxx.xxx.xxx:zpool1/svr-lf-nas/vol1-nfs
dst_0_plan      = 7days=>1day
enabled         = on
mbuffer         = /usr/bin/mbuffer
mbuffer_size    = 1G
post_znap_cmd   = off
pre_znap_cmd    = off
recursive       = on
src             = zpool1/vol1-nfs
src_plan        = 6days=>8hours,7days=>1day
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0

However, znapzend ends up sending snapshots to the dst every 8 hours. Is there any way to create a src snapshot plan that does not get replicated to dst?

Seems my issue may be related to issue #144

**Comment by redmop** [comment]
Znapzend doesn't support that.
