### ISSUE TITLE
Code review -  destroySnapshots - check that $dataSet is a snapshot before destroying it

### ISSUE THREAD

**Issue by Beneter** [oetiker/znapzend#401]
I am currently doing a code review of znapzend, without having much of experience in Perl.

https://github.com/oetiker/znapzend/blob/4c758e6b330a0f8b607630a57e9a196fa61863a9/lib/ZnapZend/ZFS.pm#L243-L247

I was wondering if `splitDataSetSnapshot` shall be invoked before destroying `$dataSet`, to be sure it is actually a snapshot and not a complete dataset.

**Comment by oetiker** [comment]
yes, looking at the code this seems to make sense ... the oracle mode does not get all that much attention I guess :)

**Comment by redmop** [comment]
Please don't remove it. I just needed it about 2 weeks ago. I had too many
snapshots and I needed Oracle mode to fix it.

**Comment by oetiker** [comment]
not intending to remove it just fixing it :-)

**Comment by redmop** [comment]
Whew! ;)

**Comment by Beneter** [comment]
> will you create a PR ?

Yes, I will for both issues. Might take me some time though... :-)
