### ISSUE TITLE
znapzend slow down horribly

### ISSUE THREAD

**Issue by mpicjohn** [oetiker/znapzend#403]
Hi everybody,

we run znapzend for some time now on (on OpenIndiana servers) to do local snapshots and send them to a remote server.

On one server we experience severe lags from time to time, that stop as soon as we disable the znapzend service.

The sever helds about 500TB of disks (one pool with about 450TB brutto HDDs, one with about 50TB of SSDs). The data is spread across roughly 2000 individual ZFS filesystems.

Do we hit some sort of a critical size?

thx for suggestions

Carsten

**Comment by moetiker** [comment]
I don't think there is a limit. only very large remove lists might be a problem.  you can check you destroy lists with znapzend --debug

**Comment by mpicjohn** [comment]
We have a debug log running and can't see any issues regarding cleanups... I'll try to look deeper into this.
