### ISSUE TITLE
Code review - ZnapZend.pm - Missing underscore

### ISSUE THREAD

**Issue by Beneter** [oetiker/znapzend#404]
I am very unsure about this... should `dst$key` really not be divided by an underscore here `(s/dst$key/dst_$key/g)`?

https://github.com/oetiker/znapzend/blob/4c758e6b330a0f8b607630a57e9a196fa61863a9/lib/ZnapZend.pm#L182
https://github.com/oetiker/znapzend/blob/4c758e6b330a0f8b607630a57e9a196fa61863a9/lib/ZnapZend.pm#L317-L318

**Comment by oetiker** [comment]
no, this is a new set of keys being generated they are separate from the dst_..._plan keys ...
