### ISSUE TITLE
Can ZnapZend continue in manualy started replication?

### ISSUE THREAD

**Issue by Harvie** [oetiker/znapzend#416]
I've done replication by hand using following commands:

```bash
zfs snapshot tank/vps/dataset@mujsnapshot
zfs send tank/vps/dataset@mujsnapshot | pv | ssh root@destination.net zfs recv -F tank/vps/dataset
```

Now i want to continue the replication automaticaly using znapzend. But i don't want to retransmit initial snapshot, because it's a lot of data. Will znapzend autodetect my manual snapshot and continue replication in incremental fashion?

**Comment by Harvie** [comment]
Turned out it works when i renamed snapshot to use naming convention like "2019-03-30-093000" on both SRC and DST machines. But i am not sure if it's safe way to do it...

Will ZFS know if i screw something and there are some incremental snapshots missing or sent in wrong order, so it will refuse to recv? Or it will just apply the incremental snapshot while creating dataset with some changes missing?

**Comment by moetiker** [comment]
I don't think is possible to apply a diff thats not have the same base... so if something is not correct it will just fail to apply ... you are always save if there is no error from the zfs side.

**Comment by Harvie** [comment]
So i don't have to ever worry that i have screwed something in the past if the last snapshot applies succesfully?

**Comment by oetiker** [comment]
You do not have to worry ... zfs will simply issue an error message
