### ISSUE TITLE
znapzendzetup does not support feature compressed

### ISSUE THREAD

**Issue by chaerle** [oetiker/znapzend#418]
There is no way to activate the feature "compressed" in znapzendzsetup (it least it is not documented anywhere). See also issue #334

**Comment by maniac0s** [comment]
I need this too

**Comment by GabrieleV** [comment]
I think it does not be activated in per source, but in the general config of the daemon.
In Debian:

 `# vi /etc/default/znapzend`

````
# Command line options for znapzend
ZNAPZENDOPTIONS="--features=compressed"
````

`#systemctl restart znapzend.service`

`#ps auxw | grep znapzend`

````
root     29278  0.1  0.3  78364 25564 ?        Ss   21:50   0:00 /usr/bin/perl /usr/bin/znapzend --autoCreation --features=compressed
 ````

**Comment by jtkoerting** [comment]
in FreeBSD you need to edit the rc.d script. extend the command_args line with the `--features` option:

`command_args="--features=compressed ..."`
