### ISSUE TITLE
Very hard to monitor znapzend in production

### ISSUE THREAD

**Issue by saurabhnanda** [oetiker/znapzend#419]
I'm building a Grafana dashboard to make sure that the following tasks are running as per schedule:

- taking a local snapshot
- sending a local snapshot

All znapzend logs are being pushed to a DB and I'm looking for the following patterns to ascertain whether these tasks were successful or not:

- snapshot worker for $DATASET$ done
- send/receive worker for $DATASET done

However, even if the send/receive fails, the following line is emitted to the logs: `send/receive worker for $DATASET done`, which makes detecting errors very difficult.

The only way to detect errors via logs is to look for the following pattern:

- ERROR: cannot send snapshots to $DATASET$ on $REMOTE$

But this is not ideal, because it will be unable to catch the case where znapzend doesn't even run.

This, coupled with https://github.com/oetiker/znapzend/issues/367 makes monitoring znapzend very difficult in production.

**Comment by matveevandrey** [comment]
I would suggest you to monitor the destination side with simple bash script which gets all zfs datasets and determines the latest snapshot exists. Than compare with MAX age allowed and warn you if needed

This kind of solution has more advantages than just relying on what sender side say (lie?)

**Comment by matveevandrey** [comment]
If I'm not mistaken I've seen some kind of ZFS Zabbix temaplates with discovery and trigger that analyze  datasets size. I'm pretty sure that template could be easily extended to store time (secs/mins/hours/days) passed sins the latest snapshot for each dataset

**Comment by GabrieleV** [comment]
I've modificed an existing template to monitoring snapshot age:
[GabrieleV/zabbix-zfs-on-linux](https://github.com/GabrieleV/zabbix-zfs-on-linux/blob/master/README.md)

**Comment by psy0rz** [comment]
ZFS-autobackup does very consistent and strict error reporting. Exit codes are also very reliable, check it out at: https://github.com/psy0rz/zfs_autobackup

There is also an example how to monitor it with Zabbix.
