### ISSUE TITLE
Build Problem on Solaris 11.4

### ISSUE THREAD

**Issue by mpicjohn** [oetiker/znapzend#421]
Build under Sol 11.4 fails. Obviously the denpendencies can not be installed as "cc" is not found. When exporting PERL_CC_PATH=/usr/bin/gcc build fails as well, due to unknown parameters by gcc.

**Comment by mattiarossi** [comment]
Hi, just ran into this, you need to install the Solaris compiler
Accept the license here: https://pkg-register.oracle.com/register/product_info/7/
and then install
developer/developerstudio-126/cc

regards

**Comment by oetiker** [comment]
this is because of the binary perl modules ... you need the compiler that has been used to build your perl binary
