### ISSUE TITLE
[Feature request] Add option "skip parent" or child only

### ISSUE THREAD

**Issue by matveevandrey** [oetiker/znapzend#432]
In some circulates it very helpful when snapshots and replication reformed down on childs only  
example:
tank\datastore\ ... dirs and files
tank\datastore\zvol1
tank\datastore\zvol2
tank\datastore\zvolN

And you need to replicate zvols only (an example vm datastore etc)

**Comment by devopstales** [comment]
+1

**Comment by matveevandrey** [comment]
+1
