### ISSUE TITLE
Runonce should have option to bypass zend_delay time for troubleshoot purpose

### ISSUE THREAD

**Issue by IronDusts** [oetiker/znapzend#437]
Hello, 

I having zend_delay option enabled for my daily backup schedule, I need to modify the configuration and remove it every time I need to troubleshoot issues using --runonce --debug. 

Otherwise every debug run I need to wait hour or two to see the send result. 

Would it be possible to add option like --nodelay or something that will bypass transfer wait for troubleshoot purpose? 

Thanks

**Comment by jimklimov** [comment]
@IronDusts : please ping back if the solution proposed in #448 works for you and does what you wanted? :)

**Comment by IronDusts** [comment]
Hello,

That's the one. It will work. Thank you very much.
