### ISSUE TITLE
Global symbol "$dataSet" requires explicit package name

### ISSUE THREAD

**Issue by c0deaddict** [oetiker/znapzend#479]
When I'm trying to run the `master` branch on NixOS I get this warning:

```
Global symbol "$dataSet" requires explicit package name (did you forget to declare "my $dataSet"?) at /nix/store/rlvxvxa9xayjz623g72awiq96j54ii11-znapzend-0.20.0alpha/lib/ZnapZend/Config.pm line 92.
Compilation failed in require at /nix/store/rlvxvxa9xayjz623g72awiq96j54ii11-znapzend-0.20.0alpha/lib/ZnapZend.pm line 6.
BEGIN failed--compilation aborted at /nix/store/rlvxvxa9xayjz623g72awiq96j54ii11-znapzend-0.20.0alpha/lib/ZnapZend.pm line 6.
Compilation failed in require at /nix/store/rlvxvxa9xayjz623g72awiq96j54ii11-znapzend-0.20.0alpha/bin/znapzend line 9.
BEGIN failed--compilation aborted at /nix/store/rlvxvxa9xayjz623g72awiq96j54ii11-znapzend-0.20.0alpha/bin/znapzend line 9.
```

Looks like this has been caused by this commit: https://github.com/oetiker/znapzend/commit/60e7afe76ed375c0b3994c29cd2283c02e0f59c4 The GitHub actions annotations are also not happy about this change.

I don't have any experience with Perl, otherwise I would make a PR.

**Comment by oetiker** [comment]
fix is in pr #480

**Comment by c0deaddict** [comment]
Nice! Thanks for the very quick response :)

**Comment by jimklimov** [comment]
Better late than never: "sorry, my bad". Seems like a copypaste issue slipped through, should have been `$backupSet->{src}` instead of `$dataSet` that was relevant elsewhere :(

**Comment by jimklimov** [comment]
Hopefully this is closeable now (or soon after vetting ;) )

**Comment by c0deaddict** [comment]
Yes, problem is solved and this ticket can be closed :+1:
