### ISSUE TITLE
Support sendRaw and other features in dataset configuration

### ISSUE THREAD

**Issue by ds6** [oetiker/znapzend#522]
If I am correct in looking at #468, the `sendRaw` feature was added to `znapzend` but has no way to be configured for `znapzendzetup`. I have an encrypted dataset that will _never_ be decrypted on the destination host, but in order for that to work with `znapzend` I need to manually pass `--features=sendRaw` to `znapzend --daemon` to be able to send these snapshots to the destination.
Again, if I am correct in this assumption, are there any plans to extend the majority of incompatible `features` flags to `znapzendzetup` and allow them to be set/parsed in dataset configuration?

**Comment by datenzar** [comment]
I'm having the same issue and would appreciate if the `sendRaw` feature was available as a dataset configuration.

In the meantime I configured the daemon by creating a `/etc/default/znapzend` with the flag as follows:

```
# Command line options for znapzend
ZNAPZENDOPTIONS="--features=sendRaw"
```

After reloading the daemon it works like a charm!

Please note: **This only works if all of your jobs should be sent raw**
