### ISSUE TITLE
dataset with a local backup plan (org.znapzend:recursive=off) wrong debug output

### ISSUE THREAD

**Issue by moetiker** [oetiker/znapzend#523]
I set `zfs set org.znapzend:recursive=off fast/vm/test` and run

`znapzend -d --runonce=fast/vm`

```
=== getBackupSet() : got 1 dataset(s) with a local backup plan
=== getBackupSet() : got 1 enabled-only dataset(s) with a local backup plan
```

but there is also the output:

```
[2020-09-22 12:14:40.94208] [1591] [debug] sending snapshots from fast/vm/test to slow/backup/vm/test
# zfs list -H -o name -t snapshot -s creation -d 1 fast/vm/test
# zfs list -H -o name -t snapshot -s creation -d 1 slow/backup/vm/test
```

it is only the output, the system does the right thing and creates no snapshot backup for `fast/vm/test`

**Comment by jimklimov** [comment]
Curious, OTOH it might be the latter action checking if the send of particular child dataset is enabled (if it is, then probably it should log that it aborted this datasend send as it is disabled, though).

The former is (probably) the discovery of "fast/vm" itself, which locally defines the backupSet policy and is "got" as such. Not sure OTOH what the "enabled-only" might refer to :)

**Comment by jimklimov** [comment]
Probably makes sense to skip the (grand...-)child of a source dataset which is explicitly disabled early in the handling routine; I think something like this was discussed in some issues or PRs earlier in the year, probably where we look for inherited dataset props up and down in the tree. 

One caveat is that if later there is a deeper child that is again enabled, we can not rely on all versions of ZFS implementations to create intermediate destination datasets if they are currently missing and we are sending them for the first time - then the intermediates have to be created manually (or even by system's `zfs create -p` if available). 

And then there is a problem of someone enabling replication of those intermediate datasets, and there's no compatible snapshot to send and none where to revert the "live" intermediate dataset on dest by `zfs recv -F` though not sure this is a practical problem (maybe it can just overwrite the link in the middle of the chain).
