### ISSUE TITLE
Use of uninitialized value in string ne at /opt/znapzend/lib/ZnapZend.pm line 777.

### ISSUE THREAD

**Issue by trijenhout** [oetiker/znapzend#524]
using latest docker container i got, 
Use of uninitialized value in string ne at /opt/znapzend/lib/ZnapZend.pm line 777.
dont think it is a problem for me i dont use the error mail 
just wanted to share this error

**Comment by jimklimov** [comment]
Thanks, I'll check. Maybe slipped through review, or due to some, I remember dropping handling of both empty-string and undef possibilities of something at that timeframe.

**Comment by jimklimov** [comment]
Right, @oetiker PR edits :) did not hit all cases...
