### ISSUE TITLE
cannot list backup config

### ISSUE THREAD

**Issue by marshalleq** [oetiker/znapzend#535]
Running znapzendzetup list (and a number of other commands) I receive the above error and no results are returned.

I can add a backup job and they are running.  It's also receiving as a target.

This is a machine with a new pool and also I have elected to use ZFS 2.0 with the new compression.  That's the only things I can see are different.  However on another machine also with a new pool and using the new ZFS 2.0 with the new compression, this does not happen.

I'm sorry there's not an error code, so it's a bit tricky to give more info.

Is there any way you can suggest for me to figure out what's going on?

Thanks,

Marshalleq

**Comment by jimklimov** [comment]
For some time in master branch (not sure about versioned releases), there is a `--debug` option for (nearly?) all modes of operation, that should expose the `zfs` commands that it tries to execute, as well as trace commentary on what `znapzend` decides based on that data.

At the very least, you would be able to run same `zfs` commands from a terminal and see if they work with new version and what markup etc. they return.
