### ISSUE TITLE
--MailErrorSummaryTo=rcpt not working

### ISSUE THREAD

**Issue by AlexanderSch90** [oetiker/znapzend#540]
Hey, 
znapsend should send me an email in case of errors. What do I need to create a mail ?! I already have = root; = admin; = myexternalMailAdress@gmx.de tried. Unfortunately there is an error everywhere when calling the program with this Option:

--MailErrorSummaryTo = rcpt

Syslog says "Unknown option": 
Feb 10 16:20:48 pve2 systemd[1]: Started ZnapZend - ZFS Backup System.
Feb 10 16:20:48 pve2 znapzend[32143]: Unknown option: mailErrorSummaryTo
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Main process exited, code=exited, status=1/FAILURE
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Failed with result 'exit-code'.
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Service RestartSec=100ms expired, scheduling restart.
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Scheduled restart job, restart counter is at 5.
Feb 10 16:20:48 pve2 systemd[1]: Stopped ZnapZend - ZFS Backup System.
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Start request repeated too quickly.
Feb 10 16:20:48 pve2 systemd[1]: znapzend.service: Failed with result 'exit-code'.
Feb 10 16:20:48 pve2 systemd[1]: Failed to start ZnapZend - ZFS Backup System.

Maybe it is because i use this version? https://github.com/Gregy/znapzend-debian
Should i make an Issue there?

**Comment by gchmurka123** [comment]
Same problem
there is an error in using sendmail (after the -t option it is wrong to use the recipient's address  )


my patch:

```
--- lib/ZnapZend.pm 2021-05-17 13:37:00.313340036 +0200
+++ lib/ZnapZend.pm.org     2021-05-17 13:36:15.636878130 +0200
@@ -783,7 +783,7 @@ my $sendRecvCleanup = sub {
             #my $mailprog = '/usr/lib/sendmail';
             my $mailprog = '/usr/sbin/sendmail';
             #my $from_address = "`id`@`hostname`" ;
-            if (open (MAIL, "|$mailprog -t")) {
+            if (open (MAIL, "|$mailprog -t " . $self->mailErrorSummaryTo)) {
                 $self->zLog->warn('Sending a copy of the report above to ' . $self->mailErrorSummaryTo);
                 print MAIL "To: " . $self->mailErrorSummaryTo . "\n";
                 #print MAIL "From: " . $from_address . "\n";
```

**Comment by oetiker** [comment]
note that this feature was only added in 0.21.0
https://github.com/oetiker/znapzend/releases/tag/v0.21.0
