### ISSUE TITLE
Mojolicious version not limited to before 9.0 on arch

### ISSUE THREAD

**Issue by mmccoo** [oetiker/znapzend#542]
I don't know that the subject is accurate, but here is what I know:

I'm on Manjaro. 
I get this in my journal:
Mojo::Reactor::Poll: Timer failed: Can't locate object method "delay" via package "Mojo::IOLoop" at /opt/znapzend/lib/Mojo/IOLoop/ForkCall.pm line 27.

Delay was removed from Mojo::IOLoop 
according to https://metacpan.org/changes/distribution/Mojolicious
9.0  2021-02-14
  - Removed Mojo::IOLoop::Delay.
 
If, instead of using the normal arch pkgbuild, I wget the 20.0 release and do configure, I get a cpanfile:
requires 'Mojolicious';

without a release qualifier that maybe should be there? Looking in configure.in of the git I see a bunch of stuff around MOJOLICIOUS_VERSION_CONSTRAINT

in arch's PKGBUILD file for znapzend, if I add this:

prepare() {
    cd "${pkgname}-${pkgver}"
    sed -i 's:@BINDIR@:/usr/bin:' "init/znapzend.service.in"
    **sed -i "s:'Mojolicious':'Mojolicious', '< 9.0':"  "cpanfile"**
}

and reinstall, it seems to work.

Note that I'm a znapzend rookie.

**Comment by oetiker** [comment]
note that this should already be fixed in master now ...
