### ISSUE TITLE
znapzendzetup edit ARRAY ref error

### ISSUE THREAD

**Issue by tpyro** [oetiker/znapzend#545]
I am getting this error on SmartOS:

./znapzendzetup edit zones/1f04fdcc-2b6d-4491-9e6d-33c03e5ac707
Can't use string ("0") as an ARRAY ref while "strict refs" in use at ./znapzendzetup line 236.

I started with the pkgsrc build but I got the same error when I built 0.20.0 myself.

**Comment by oetiker** [comment]
can you please try with master

**Comment by tpyro** [comment]
Still getting the same error. It seems to be getting this (via Config.pm) where it's expecting the array ref:

    # Note/FIXME? If there were ZFS errors getting some of several
    # requested datasets, but at least one succeeded, the result is OK.
    if (scalar(@{$self->backupSets}) == 0) {
        return 0; # false
    }

These were my steps: 

    git clone https://github.com/oetiker/znapzend.git
    cd znapzend/
    ./bootstrap.sh
    ./configure --prefix=/opt/znapzend-20210520

**Comment by simobgl** [comment]
same issue here. Built from master.
