### ISSUE TITLE
OS X Big Sur fixes (launchd)

### ISSUE THREAD

**Issue by xenophon61** [oetiker/znapzend#555]
Hi, and thanks for a great project!

Two issues with a (fresh, current) Big Sur installation, running the latest OpenZFSonOSX. Both easily fixable :-)

**Installation error**: 'make install' throws a permission error on the /opt/znapzend-0.21.0/ folder

**Launchd Daemon error**: the default one, created under the 'init' directory (i.e. org.znapzend.plist), copied in the /Library/LaunchDaemons/ folder, does not work; the process exits with an error=78 which corresponds to a launchd 'Function not implemented' error.

The fix for the daemon, is to modify the following:
`<key>PATH</key>
		<string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>`
should read:
`		<key>PATH</key>
		<string>/usr/local/zfs/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>`
... and the actual command
`<key>ProgramArguments</key>
	<array>
		<string>/opt/znapzend-0.21.0/bin/org.znapzend</string>
	</array>`
should be changed to:
`<key>ProgramArguments</key>
	<array>
		<string>/opt/znapzend-0.21.0/bin/znapzend</string>
	</array>`

Once again, thanks! With greetings from Athens,
Xen

**Comment by xenophon61** [comment]
One more thing: the command to send -HUP is as follows:

sudo launchctl kill -HUP system/org.znapzend

**Comment by oetiker** [comment]
@xenophon61 could you provide a PR ?

**Comment by xenophon61** [comment]
Sorry for the dumb question, but what is a "PR"?

Xen

**Comment by oetiker** [comment]
A Pull Request (PR) is how you can submit changes to the project ... just open the relevant file in github, edit it, and submit ... github will offer guidance.

**Comment by oetiker** [comment]
Click here: https://github.com/oetiker/znapzend/edit/master/init/org.znapzend.plist.in and edit away

**Comment by oetiker** [comment]
In that case, you can add a .in extension to the file, and then add the file to the list of files in configure.ac to be written out at build time ... make sure to modify any mention of the file in Makefile.am if there is any (just not in a position to check it)

You can now use any @xxxx@ tags in the body of the file ... take any Makefile.in as an example.

**Comment by xenophon61** [comment]
So many thanks for your time!

I'm kind of hesitant to touch the code, so I'll attempt to modify the ReadMe (and create my first PR of sorts ;-)

I truly appreciate your help, as well as the chance to engage in a GitHub project -- thank you once again!

Can't help but reminisce on my 6502 assembly language coding days ;-)
