### ISSUE TITLE
znapzendzetup edit data : ERROR: cannot get backup config

### ISSUE THREAD

**Issue by hallux4** [oetiker/znapzend#557]
Hi,

I made a mistake while editing the znapzendzetup config.

```
znapzendzetup edit data
*** backup plan: data ***
          #dst_a = root@serveur_ip:backup/zfs_volume
     #dst_a_plan = 15days=>1days
     
     Do you want to save this backup set [y/N]? y
cannot set property for 'data': invalid property 'org.znapzend:#dst_a_plan'
ERROR: could not set property #dst_a_plan on data
```

And now I cannot edit the config anymore.

```
znapzendzetup edit data
ERROR: cannot get backup config
```

Is there a way to recover from this without deleting the config ?

Regards

**Comment by Dacesilian** [comment]
Hello, if znapzendzetup delete doesn't work, you probably have to delete all `org.znapzend:` properties (`zfs get all data`).

**Comment by hallux4** [comment]
the `znapzendzetup delete data` worked.
I recreated the config without the remote destination.
