### ISSUE TITLE
Missing znapzend.default file

### ISSUE THREAD

**Issue by kevdogg** [oetiker/znapzend#569]
I was reading the documentation regarding setup using systemd service file.  In the documentation it states:

> " .... copy znapzend.default to /etc/default/znapzend and edit it."

I'm using arch linux and installed znapzend via the AUR however no where on my system can I find the znapzend.default file.  The documentation stated this would be generated, but I certainly cant find it.  

Potential issue since the znapzend.service file contains the following:

```
EnvironmentFile=-/etc/default/znapzend
ExecStart=/opt/znapzend/bin/znapzend $ZNAPZENDOPTIONS
```

The environmental file doesn't exist nor does the env variable $ZNAPZENDOPTIONS

**Comment by oetiker** [comment]
@kevdogg the file does exist in the official tar.gz archive, and also here on github ... I guess there is something missing in AUR.
