### ISSUE TITLE
znapzendzetup: backup plan rendered unusable 

### ISSUE THREAD

**Issue by rzerres** [oetiker/znapzend#572]
# Abstract

On a working environment i had to edit an already active backup plan (`znapzendzetup edit myplan`).

I was mistaken and tried to `comment out` a disfunctional destination using a hash sign in front of the `dst` line in question inside the editor. After writing the buffer end ending the editor session, the given destination-plan isn't accessible any more. I can't edit or delete it. Can't create a new one, since the given data are blocking. 

 Your are right, i should have used the intended `znapzendzetup disable-dest <src_dataset> myplan`. But now, the configuration is rendered unusable and unfunctional. 
 
# Expectation 

`znapzendzetup` should have rejected to write back the incorrect backup plan or should have deleted the corrupt dstination lines to keep a syntactical correct definition of the backup plan.

# Question

* Where does `znapzynczetup` persitently store the plan configuration? Is it possible to correct the corrupt information?
* Is it possible to force the deletion of corrupt plan? 
   Right now `znapzendzetup list --recursive` omits the malformated backup plan.

# System information
OS: Ubuntu 20.04.3 LTS
Kernel: Linux 5.13.0-1010-oem
ZFS: zfs-2.1.2-0york0~20.04
ZFS-Mod: zfs-kmod-2.1.1-0york0-20.04
ZnapZync: znapzend-0.21.1

**Comment by moetiker** [comment]
You can get the wrong zfs properties with:

`zfs get org.znapzend:src_plan poo/path`

and fix it with

`zfs get org.znapzend:src_plan poo/path value`
