### ISSUE TITLE
📦 Official Packages and Debian Repository

### ISSUE THREAD

**Issue by Harvie** [oetiker/znapzend#586]
Hello,
i would really love to see official repository with Debian builds...
Everytime i have some problems with znapzend it's usualy because Debian was upgraded on server, but nobody rebuild znapzend to run on latest Debian... I've just found that znapzend was not running on my server for last 12 months... Don't ask how i figured :-(

```
# znapzend --help
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xed00080)
```

I know this is not your fault, but it would make znapzend so much more useful to have official binary distribution.

**Comment by oetiker** [comment]
That would be great ... will be glad to give support!

**Comment by Harvie** [comment]
There is already this guy doing releases:
https://github.com/Gregy/znapzend-debian

perhaps you can take the scripts and use them to build and release officialy builds.
