### ISSUE TITLE
mbuffer: "operation not supported" message and not sure how to troubleshoot

### ISSUE THREAD

**Issue by emory** [oetiker/znapzend#612]
hello,

i'm using mbuffer on macOS in my znapzend configuration via:

     mbuffer=/usr/local/bin/mbuffer
     mbuffer_size=1G

and when i'm running `znapzend --debug` i see error messages for my configurations using mbuffer, ==redaction via `…`==:

```
# zfs send -I cascade/…/notes@2023-07-26-113000 cascade/…/notes@2023-07-26-114500|/usr/local/bin/mbuffer -q -s 256k -W 600 -m 1G|zfs recv -F succor/localbackup/iow/icon/cascade/…/notes
mbuffer: warning: unable to sync <stdout>: Operation not supported
mbuffer: warning: unable to sync <stdout>: Operation not supported
# zfs list -H -o name -t snapshot cascade/av@2023-07-26-114500
```
my `mbuffer` binary i built myself per the instructions in a GitHub issue: https://github.com/ilovezfs/mbuffer-osx/issues/1

the version of my local `mbuffer` is `20141227`, i've built it on Apple Silicon and intel and i use openzfs for macOS on two workstations. i use `znapzend` for local pool-to-pool backups and plan to begin using it for host-to-host, i hadn't noticed the error until recently. i haven't setup any launchd jobs or anything yet, i foreground and `--debug` in a tmux pane while i get familiar still.

**Comment by lundman** [comment]
comes from
`err = fsync(fd);`
spit out by
`warningmsg("unable to sync %s: %s\n",d->arg,strerror(errno));`

but you are already in `terminateSender()` at this point. So either it worked, and you are getting noise at the end, or something else went wrong.

**Comment by xenophon61** [comment]
Sorry for the noob question - is it still possible to compile for MacOS? If so, how? (the 2018 instructions don't appear to work).

TIA
