### ISSUE TITLE
[ feature request ] Rewrite in Go or Rust

### ISSUE THREAD

**Issue by yonas** [oetiker/znapzend#660]
Open request to anyone who has time to work on this.

**Comment by jimklimov** [comment]
As formulated, unlikely to ever happen (the "has time" part is a frequent show-stopper) :)

Also, what would the tangible benefits to the project be, to outweigh several months of work (other than learning a new language etc.)?

**Comment by oetiker** [comment]
I would suggest rust! the clear benefit would: no runtime

**Comment by raoulb** [comment]
Would be awesome.
