### ISSUE TITLE
[ feature request ] Make znapzendzetup to be able to create backup plans without prompting for confirmation

### ISSUE THREAD

**Issue by IronDusts** [oetiker/znapzend#665]
For the purpose of automation the znapzendzetup tool must be able to create backup plans without prompting for confirmation via keyboard input. 

Please add a switch like --confirm or something similar so it can be executed via automation scripts.

**Comment by mtelka** [comment]
I think you should look at the `--donotask` option.

**Comment by IronDusts** [comment]
It worked with --donotask, didn't know it exists and didn't find it in the documentation. 

Thanks
