### ISSUE TITLE
arm64 build support

### ISSUE THREAD

**Issue by sunjam** [oetiker/znapzend#676]
Hey, nice project.  Wondering about arm64 / armv8 support.

Thanks either way for considering!

**Comment by jimklimov** [comment]
Um, what was the question again? :D 

Did you try? Did something fail? What are the logs and other clues?

OTOH, this project being a Perl script (program and lib modules) using ZFS tools provided by the OS, there should not be any portability problem with it as long as (Open)ZFS implementation is same as elsewhere - with a wide range (like 15+ years of difference) of implementation nuances supported by configurable tweaks.

There *may* be portability questions about Perl versions available on different platforms, and certain versions needed by libraries used by the project, but that's all I can think of right now.
