### ISSUE TITLE
exceptions under root of --recursive

### ISSUE THREAD

**Issue by rottegift** [oetiker/znapzend#87]
It would be nice if one could change one or more of the inherited properties under a dataset with znapzend.org:recursive=on and have znapzend and znapzendzetup like that.

**Comment by znek** [comment]
I just tried znapzend and immediately stumbled across this as well. It's probably related to being used to zetaback before, as this allows suchs exceptions.

I get that this point is a misunderstanding and instead is driven by znapzend's design, however, I too have ~ 100 filesystems in a hierarchy containing a few transient filesystems (tmp and obj trees, which arguably could be moved elsewhere, but happen to be where they are for historicaly reasons), where the above proposal would come in very handy.
