### ISSUE TITLE
per-dst ssh options

### ISSUE THREAD

**Issue by rottegift** [oetiker/znapzend#90]
The defaults in ZFS.pm (-o Compression=yes -o CompressionLevel=1 -o Cipher=arcfour -o batchMode=yes -o ConnectTimeout=3) might be inappropriate for some dsts, so it may be useful to override them on a per-dst basis.

For instance, I get an almost order of magnitude greater throughput using -o Compression=no -o Cipher=aes128-gcm@openssh.com between two Mac OS X boxes using OpenSSH_6.6.1p1, OpenSSL 1.0.1i 6 Aug 2014.    I obviously can't use that cipher with an OmniOS box.    Also, some destinations might not allow arcfour.

**Comment by nhuff** [comment]
As another data point we see a 20x increase in transfer speed by disabling the compression options for ssh.

**Comment by Ryushin** [comment]
it would be nice to see this sooner then later.  Modern processors have enhancements for AES.

As an immediate step, it would be nice to see moving to arcfour128 or arcfour256.
http://security.stackexchange.com/questions/26765/what-are-the-differences-between-the-arcfour-arcfour128-and-arcfour256-ciphers

We will tunnel the the connections through OpenVPN in the mean time.

**Comment by oetiker** [comment]
for custom settings, just use `.ssh/config` and set whatever cipher and compression setting that works for you.

**Comment by Ryushin** [comment]
Because I think this is a security issue, I think it should be moved to a feature request and not closed.  Your call though.

**Comment by oetiker** [comment]
I have removed the settings ... in 93130b6 so znapzend will now use whatever defaults you have set in you ssh ... that is why I closed it.
